# Needed to pass db credentials as secrets
apiVersion: k8up.io/v1
kind: PodConfig
metadata:
  name: backup-env-config-immich-db
  namespace: cnpg
spec:
  template:
    spec:
      containers:
        - env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: bot-immich-pswd
                  key: password
            - name: PGUSER
              value: bot_immich
          securityContext:
            allowPrivilegeEscalation: true

# spec:
#   template:
#     spec:
#       containers:
#           env:
#             - name: PGUSER
#               valueFrom:
#                 secretKeyRef:
#                   name: bot-immich-pswd
#                   key: username
#             - name: PGPASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: bot-immich-pswd
#                   key: password
#             - name: PGDATABASE
#               value: immich
#             - name: PGHOST
#               value: cnpg-rw-lb.cnpg.svc.cluster.local # or vchord-postgres.pengiuns.com
#             - name: PGPORT
#               value: "5432"
#       restartPolicy: Never
