# Needed to pass db credentials as secrets
apiVersion: k8up.io/v1
kind: PodConfig
metadata:
  name: backup-env-config
  namespace: cnpg
spec:
  template:
    spec:
      containers:
        - name: backup
          env:
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: bot-immich-pswd
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: bot-immich-pswd
                  key: password
            - name: PGDATABASE
              value: immich
            - name: PGHOST
              value: cnpg-rw-lb.cnpg.svc.cluster.local # or vchord-postgres.pengiuns.com
            - name: PGPORT
              value: "5432"
      restartPolicy: Never
