{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "bot-jerry-pswd",
    "namespace": "cnpg",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "bot-jerry-pswd",
        "namespace": "cnpg",
        "creationTimestamp": null
      },
      "type": "kubernetes.io/basic-auth"
    },
    "encryptedData": {
      "password": "AgCS3w/TpawArH+ICP04ZJy93XRCOJshviySKizyZwPaJTMX6B249vcyF1rznX1zBh8J+VrCqAt/lxtOv39/wvlRgVpNy6jSE2/QA2IDO06CA+HQy0r6zAH8iPR8suBmBVzMXewmSfcUukQKaoqOyXMTvpATqf6ynfsryjP0/do6N6dV+WSPfO2TaCLW4FupOE+qxbGFbxt2d4tOu2943lSHgXTCtv5jL2FMdaYv77E12+QOzRcnKIT4SqJOLSLLABt4i5uaD/yzV5KB3oSR4VIBfG9kXzNFRCS8ukxpSowP4TVnE53Jyslbm7SFWUTTrNUsv2A43QTawcOAwN0jAOT5n18OBFnFN2XXEg0XUjmn8Qt0QgLPtcv+ltATHAECPuTOrt1rPHRirSdYeK6ta3zSxVgEac5VH69TVyB/W6UFTgJPRgWOdWSGzs2ZFOgFgxydX8p3IYvTd9y8O9dVfXHRxEplc3Y8uyGMbdVUh/f0yKlHscOWKf5DsmzMXKcntP+Sd6oGhcmwEkXgUjNVZL4QRUieawjAxczcvFqNnKNCCupuy6+O2izSaYeaeiRbi6T1bfoiZw8Lrbz6CAox5aRwuVuyf3MFQr2aA61DYuqWmT/VBNyjbz+fbTak7nfZEU1cAP3PFQTIq1qorSYYY4U3hBxJkiUxfs5pTr7RhBJ+3/RPPeJtJ75Hdc9nVHij7hDRhAiIRKFfXXBvOdxEMT4q6qVLKh4=",
      "username": "AgATysP3/pB+SpM113MuJBGz2OIAN6AFcaIyQksVFYuHZ3pXOYCt744cIX5kqo5KLvNKrZ2TvE6HgE7x9M0qW7Y7Y/UHw7phQi/6o16vBXKjbQlDHCRGdVKtZQ5OnwRCWWIwijNX3/COOecgxv6dZ6hEWJBLhMnOQ0uE4xjPjo45E7xDTOm1LrhU05rTTILiDjwOZtonoHgzqTMhOC9ce2+M1TDlBPDSpNey4rgDuDaEXiyQ4VLYyG9YvKtOuVNmXZcs3yxQNfMkPD1vpvzOKPUSprzTF4gck6FSQ9UsdVpjjZEaaZ+QGuarpErSmgsLWg4HSfzQ3BeKXMjjn+FkGcw4U9v+L2N3lJSqpH0tbMiBDIe8Ass5ktdDlAZPOcDhsXZBG2A+5RSy3tjGvoSaVllJypP+QRB3sUdZ4jycgMaoGf93tCufFJJB+qWzQ4i1g7dmeCCwbiNQ06wcbRy1O0LRDOZ4l1R2ftpalCj9pFmLhRauLvpP4DczTccwgx7HgVWBgStax2PPJVmb2LuRwJVaeV9OVDN05ZCpVpmWtZgDXrAEfinEPucy9FqbZv/z25DeL/OT/vjJxghkwFE5xbIIPXBLmoM6FyjdOG0BwyZrMkLJuUIA/M8t7NWHxt2G9rUwXYv5rpteau3mJkA/N7iXq83K0vx071UCDIyLnDfk0AnEaQ2FF4x0gzmXMw96ExDN3UF/pEQMq9c="
    }
  }
}
