{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "bot-metabase-pswd",
    "namespace": "cnpg",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "bot-metabase-pswd",
        "namespace": "cnpg",
        "creationTimestamp": null,
        "annotations": {
          "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
          "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true",
          "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "metabase"
        }
      },
      "type": "kubernetes.io/basic-auth"
    },
    "encryptedData": {
      "bot_metabase_pswd": "AgBBoCUOHj02om+o6NBm7wvtwqUvCAY/Lr/aPJ8B6PiJEqXCEfw9B28DRdYBNhi5801yZOADMISjh713h9oXOTrh7w9476sCViNo2ivLNH6epLLK9qfsIv1WMJ3fvdraOZOXkgXrrGVLAhjmniigpxYbSH8H6Zwf2dQm6+tKGSMm6FNHK6j47ZPgUn5ZHwXZ7+fTiy5lR6waenVroTrKLwAIjuI/h+RXbybCWy/Kd7mBkENssBZTbg35kbl+pz/YvzKP8pp+FutuLCNxyr21+LBl+DzeXGf59SfJNomeo2ILu4P9I/edcgq+1odILlM8os/lGDC2kiXupWpc0Sva3ImsbBxYe1iIwrxNYKLuFDYLOzEA4ew5dH5ui+QSuTHyBBdCCZHJ11IRHHhdICH34MqL2xyYEbNXqPi3QBU/qhwy7uUL+Fr0Pphsniiop/Bhs6/Q8D7eQS+x7AR1MXTt6DAv5f/vVSRuVS8eHzWhQ64LJy39Acjy/pqnQlgbYiUxGs27GLL79ZlA18QOZwJe0FHd0W2/J6K0oCQhDCjebdyzHfsmq3hik9zRpU7+GjrR6YxccDD+glqIDHJQV6EomyxnWQA4DtCwUgbW8yR24ADF5A36U1l1r3+bqSJyejjZCt7Yj4k0Z3bwFbxNQA3/x44c2O4QMBDmnCj06vDpUnsn5N6cXDX7vjASmv2+fjDmNndf55K6H7UmyG6DEBwWverCVPV0QE9lEQ==",
      "bot_metabase_user": "AgASQrs9tRDY8/qt4WFekBgsDC2DaT7DV6dHocEfnwe1tW+MpO+6QHizpFKokv9K/m4BNKIVcwZyTHMpSGPObSqOCrWA8ACta6I76iihiWMNYK1corIqCwj/NViidjUsdz7moPAAJ2TovMrBvkhpvC5mTyh263WLqtuo93q43q84KtLxrjbjCZwK+jWqPXvu7hADU+bvuiaXIxfhcgA0uKS4wMqc7W2RAfVy3xUzVbjWkKIkbXqKcK9m+lxVJ/6E7XmBI2OA4dZyyGm2AHAZSeFAVSfD1i7PEKwCfo56NnCU39OykgpUXp4BJWepXQT2PWOKyRPUVKJmHu5gJ+aw/zuwyte+jAG+kWul7Z331zNCj66sYXh2/9hlfUGKdVBnU7IioR7tVR9FTHiQlC0n/fAAccghz3zHtZbGJqEgpYXl/AkH/y0Qg9iQvXr4atUdNkNTjq8Dn1a66lOk8EtSkLm0nctxJJmyfQCoyuWfcv7IhfDOtqzZ5ixmApma8qdim+VN8zixdao+5qJs3Y9lQ63sVnAL6CP2k4e1Tzd/YRgFWONMgD73L7psxMlSbIZ0xmxeUq8MCYlf2wzY7xBDmuMH5YcPIJ/EwWycZqBMBYRTgK4WvO6eHw7iyknzbqcFL4eKaWgC43heb6UVYUqhBMHfEC+OmrmfsJFcU1rWJk5ee3pAzfzZAJGYA7SFj6L9HuKQ0gh42JKgeCUw7Ww="
    }
  }
}
