{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "bot-immich-pswd",
    "namespace": "cnpg",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "bot-immich-pswd",
        "namespace": "cnpg",
        "creationTimestamp": null
      },
      "type": "kubernetes.io/basic-auth"
    },
    "encryptedData": {
      "password": "AgBdHdkWYCc1wIyo8dTs4n7xsoANampM9fzQtmjCHTj5w9TI2MH1pOBSgUDutVeoXtclZhCBcLoMVM7p2kYzOrAZ7dqOmcYZUJ5BbRMOFQzOk3E9H4dKGHu4iyIjwa81VJ2xpIEOFNOnKTQ+CAa0ym00ee0HsSPXdtsvLsfv0lKPfZKoH1dL6rN62gKVAEpdwNFS++2eosQUOHy0+yCaTRObMpKREEYH+3IuX880uAjIcXFEFEoCVtCRM4wrU20FvJIcQLmno5rebJBc1Rf/gxrjU9HlD2x1ZjS05iLlEFNa80vsWx4T101epT7UB2pJdZjT42QJqSqOlHCObOsZFUMMK4JDVtLSUotahiEfQCebkht8X/TM1V/bkeHOMJW5vR4+afycdc5sL8wPdLjLUIGrQO3PUUCr01slJDELBHcWGc9g7vLRRvGnEHuE4RwzsCl1+1/QEqA8xmOW2XvNxiJgJVm1s+xAMPnH3dLhME+amU8UxXgS/O1r6ncozFV7dcgFJpUhR0KrL7mkvE/3jt+HTBFNmxGwZL0/9QU/fEy1toGwfC6JkBbEfpJrXC6vJZR1J1oBtdRLGnGcOsqZxamq8nUfSiPVt8LR+csZMi+XC8oSL8ZDZDrxlE1uiuDllZ7u8mVeoD4DCVeFOzRTCsVndhezq/UfzRfKjpimMFK9/MJ0ns7nEyTSXyWozxoKdJj8iGxZomutEEoJBfndNch/L29Vjc9nOZdGe/Ok10I=",
      "username": "AgA6cno7GnjAy2c4aikQ31U3g9pwkiLO9Sz9LrBvgW9iAB7I+PTqGKKRkatWBA7w1Vm7FArKs19o4hvOppxnF4hlVzGsEXqY6m/JyhsHTzKNWBzx47PD3NuQU3JZ2vl2x3GmTPjJv6NllMH22+MARG+oZ8bEfw9XSDfChMgijVR5/LOsjE7bQC0CulJ+LIm/Wfeh4u1cD6q962sTlt42XftAybDzt9aDZwU3FqFZdL3H2CHdDsWluDAVEkAt2zSBav74bmqFYJ5W8e53cWaHME6fd6YRcSTeSuftmKXR49iYls+Q+1i/b/7hRHgl+0URKTQyw6lgK15pbKuYFkGFaL1XEfbgC/fl3nRfQESCjVr9/rSCsErAOimai5XbK/mOWiLgRHFYraDWCysW8sgV/cEuVecXhSnoXJFkwXiLZscTM1EtbVEmtE2Sh4Sc0S22HMsQ6QBNK9+ljYhtoXjJP/ovS5UGx9m36XPpaLqcFR8GJNKpuEYecKR7i1yA/0nkZ4z8gOgXygipdsbPEwq5FTJN8EAvzUXcpQdhWbkFKlwn9LP9hB5jPnV8x7cNAuJcu4RzKWE2eNQKKLFimKuJDfzylvEpQd5+f/Ln4iHCrv4kBBEbtPF0yFoL3i3qi8M+VqLT4kt277O36JpJjvKT9Tmh17GbiVfHnSHju5HO4H8NaiBZBg4igYSIre2k8oww5YQos7Mcv0gqvKhU"
    }
  }
}
