apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg
resources:
  - bot_immich_pswd.yaml
  - bot_metabase_pswd.yaml
  - bot_jerry_pswd.yaml
  - release.yaml
  - superuser-pswd.yaml