apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg
resources:
  # - config-init-sql.yaml
  - pvc-cnpg-config.yaml
  - release.yaml
  - secret-cnpg.yaml
  - secret-cnpg.yaml