apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg
  namespace: cnpg
spec:
  instances: 1
  imageName: "tensorchord/vchord-suite:pg17-20250901"
  imagePullPolicy: Always
  storage:
    size: 5Gi # required, but we’ll override with PVC below
    pvcTemplate:
      spec:
        volumeName: pvc-cnpg-cluster
        resources:
          requests:
            storage: 5Gi # Do I need it twice?
  bootstrap:
    initdb:
      database: immich # CREATE DATABASE immich;
      owner: bot_immich # CREATE ROLE bot_immich; --will be owner
      secret:
        name: bot-immich-pswd
      extensions:
        - vchord
        - pg_tokenizer
        - vchord_bm25
      # TODO: Add later
      # postInitSQL:
      #   - configMapRef:
      #       name: myuser-init-sql
      #       key: init.sql
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
    roles:
      - name: myuser
        superuser: false
        createdb: true
        login: true
        passwordSecret:
          name: myuser-secret
    resources: 
      requests:
        memory: "2Gi"  
        cpu: "200m"      
      limits:
        memory: "3Gi"  
        cpu: "500m"
    
    monitoring:
      # -- Whether to enable monitoring
      enabled: true

  serviceTemplates:
  # Cluster creates automatically 
  # my-postgres-rw → service for writes (primary)
  # my-postgres-ro → service for reads (replicas, if any)
  # my-postgres → headless service (all instances)
    - metadata:
        name: my-postgres-rw
        annotations:
          external-dns.alpha.kubernetes.io/hostname: vchord-postgres.${DOMAIN_NAME}
      spec:
        type: LoadBalancer
        loadBalancerIP: 192.168.178.190 # pick from `k get ipaddresspool -A`
        ports:
          - name: postgresql
            port: 5432
            targetPort: 5432
