{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "superuser-pswd",
    "namespace": "cnpg",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "superuser-pswd",
        "namespace": "cnpg",
        "creationTimestamp": null
      },
      "type": "kubernetes.io/basic-auth"
    },
    "encryptedData": {
      "password": "AgBgndo65hRwPiVnNjQrtdBoghhEKSD5Vcd+S92Z04WzkfredwFguzCdoJSxJVAof/oEitSJnx5QhNEXnVdy1ogis0IHLnlNmtSHxF4qG30GhhMuo8IzKnlxGQNSGFcPASU/LEmBIx6ezq6aqSMdCH5ONkTwLJLqisIJs1/WfjjjgpGDMo/Nu7Vd+ydgJ4l9pZ+RdXF/ROmzd3fHYRUIi0klV02i33o/ifer/VYSR6dtiNS6NPi5nImt3wWPyPHRx1z2hkgq19Xz29lphAwlJtqfZfEduMhG9YLswv+4cw1TP0K+VcN75D5PryvbuaU3e1VQ7VIRu+iWIBIJGa2ust9pThiY43Fp9m2K/c3pj05sN+1FX7tCRKAjSVbfNi1xOl/GXki2e6GuuQ4Z2PLNOle49lM2SP2QDJ0prcfXxyt6CHZabN+7lDqbSKQmuUPDxu/zPrsR+zq+AtjRTCMI7SLy+YsSO9NTyRdg5Qh1c7EVq2xlgQvdwNIblmOQvP+7vPASdu2M8tI/SpPWGKgEbdS+ko1p/6sqJsxDNrcWeyBSfLsTziffTC6S2MsNt+zY4NKcMgCMGBYqGskEoK0oCWbX5kMrOhkTzr58vvv+tbhs3m/yGndDJpy8FORiu4UkdRZLhSf4wiLuyconhX+iYKlazilQR6ajq+rMBHXAU1YXv8p4t4ouCF+75EavcRvBkXDjdr1kWzBnkXfbaBNbWTRsa4gy1mhsaQ==",
      "username": "AgCIA35e6eGmV8d+SZhePOi5JH6O8X5gnpHFnYx8SM93j1LQdp0CW5GnrP98vFvNUT/CfVYvJAeZxJXd6YCtpnUz8GGsVHBp8jxGUzx4UumGNJL0V0fwtqCsu37YSV1KR36qo2ECEZEhWVAaYrWm54AQPNZEAQi3v2IhEirM7KM6L8Wbb+cuSfemx2k0w7DBIVRw38ODdgRsztDp+hjJMzwuDXQz180jR+rAbRF+LUtcCPjcnQCM+u6oPvFP9GbNvkvpYWZ2ZIXczwXFQcZUJWdJ/411MsWsIawXbKMv3bvoaPkSdpBszYP7R5oH5LHjZtEQaDr88wv17ouhAo5F/7rzIi7aqJa7bkjE9Wy6BBlqA4dfatO6WVnSb/g6hUyUS1fhikdU5YjsZzkb3F2/zPTGf/QndQzO9C8jciUsZIy8IjWJYlMl4LoaNuJPB8V9RnhjZM+/MjWXdzj7ZU5gNky3/ymDALvjSloyURJ+xTxRWGzsO178H4jF0dLUr43o458JmJuY06nOUQzAV6HUVVODiZDDVIyglI9s2xTuiaM3F457zfXRAX+52XH/4gYI26/x2G32Shk2Jtv2K9axTe4JSsUlNFws+y6t6HJPJWbsAlbJrz3sqwPtVUn/I5yH4y5FRu7I828MCu7Q1DDt9zk8GKEQj96RhtHmQkQIhZTnzLLfnbzOFm7L4MUdXWRvIGpDPgJBP0Zjmw=="
    }
  }
}
