{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "pocket-id-encryption-key",
    "namespace": "pocket-id",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "pocket-id-encryption-key",
        "namespace": "pocket-id",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "ENCRYPTION_KEY": "AgCFznLSasgQ050kq/FPSlg+aTZPbKJKu65JE04V2a+cuT988yW42jcQc/czX/j2mfYdXKlgp5tArpxeZf3jGTetgeb4W7psyMhloysZPbqAOmQOjo5O3eM1CwAK/5uCO8F05eraLQTmDhSQukGL3cJVVYIPIjw1HjzNiqQhGWrLlRMQkh+K/+5oaa52o6DadyrSVjYVggpazCctBV22sGUaAJ3QGQtPKLvPbVO2DR5wF3SEXIh4b8BupSI9wmEtII+DueMe765QJ7TDA9+8i1iQB8xPtqJ2IiiDgFu9ZtikJc4+fYrdhs5OJtr1nKqaufY0GF7sCbnjwdroNyNOQs34VoGWBpg+cquLCtg45Pw46QnyCN3fhIelQd1KZfZtqeMc7WUEhqJYm7Clym7yM6zvto/s/D68u3RJ7i5TSW3k6chibTXehkBosFnjVfoAdCUsumbIK9M2M6rtBF1qaEsCeXcSMVfTx3dbA0z6FmlEM74HlIRlOc3J36aKY5Lno4eqbD+suOjzWNzmAQ/S9M0K5E3aZsHRsPgO544G2s7VHU6OT0Ulmyfw3mbHnk4xniC9x5Wf8yCUeLw3mC02xCZD8fyiU3CmmqoQnlghrEGVBTMYuCo9PUsqDiEfoCg936lrHY4IUlxsPim2HzqQsiw8b1XuhAK02RoVtXD3sT48ZF8xh2ytdz+9RXON3ALVMVmSg6TWRjPz/JCWIxQd/74nwtrPVAlcOmeELxQEtQetaBoh/plGFVPg0ZsvMQ=="
    }
  }
}
