apiVersion: v1
kind: Service
metadata:
  name: cnpg-external
  namespace: immich
  annotations:
    external-dns.alpha.kubernetes.io/hostname: cnpg.${DOMAIN_NAME}
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.178.151 # pick from `k get ipaddresspool -A`
  selector:
    cnpg.io/cluster: cnpg # must match my cluster name
    role: primary
  ports:
    - name: cnpg
      port: 5432
      targetPort: 5432
