kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-cnpg
  namespace: immich
spec:
  storageClassName: local-hostpath-kevin
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
