kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-trilium
  namespace: trilium
spec:
  storageClassName: local-hostpath-kevin
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
