{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-api-token",
    "namespace": "external-dns",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-api-token",
        "namespace": "external-dns",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "cloudflare_api_token": "AgA1UGIDfZd11Ci66tm50tT2Nja7C5aDlyjEiVMg6Z9y4+2YhNLSw/lLWwOeQwuzhN+difOpSU6Y0Ix2MAXgOKrSQWtp/SY7xZu/XasQC2nT+x1cWIP/goTAnrMKa2LC1iE11bYzOxXjjwRYbU0hIqJTxQ0UuEqlu/OdNVbu/4e45a6vdE9u8gs1qajNTOXoYNYeLWVuI076KACnhLjjnvgoXsLzqhmjaBJ0f9Muh+NTBPdftbAQxtAO1uekVzVGjhKcs/NCJEWnLiFFyZgBT77amo/miXJKcxz75+I+mDqfXqz39SqlplCc7AP5JgBR4fweQdj61OaU+FSUe4huX6Qyy5U9BT87THK5Y9hzQ4bm9qbdvLPwD8ZiRApNseFqsXHvqM0wkDWMp63I/uUA40dSGqlY7mEPBXR+/FwoYpMZra+2kgCTLQRptoK9ULO4KX/pRl8sAZUlu0Q+47JhOfTFhpw6XUNnu1ZebcKTZS0O9PbnFk20HJ8qQIeo+aDWHZWGitkxH3/Md2XC0tNRPxahxhk7rARXf5s2LoHXkaciX2raFE8pULI4iDy7oaAACc6MSr0Ydn8tuiIWpWZHo3+J+DdRmShQvIQ06HsWOo/+lggN/q5pi4IG4SQROzqz+JZYmZWd4WsMdtLIFHaeDwOIFNVOI5tKc5eJON0GHtPLG2M4WWNK+gwLYpgygyZy1z+dpgbGwar+kcHkRB4dMBKxpgtewEoosbiLUCn9t1DNDG9ScmZbun1T"
    }
  }
}
