{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-api-token",
    "namespace": "external-dns",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-api-token",
        "namespace": "external-dns",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "cloudflare_api_token": "AgAFleXNb2ofv4g0rOKuTDtPibra1Gnz7VsGwNJcu6/zSNR7zTzTbKF2/PXldX3cLWzqylu4vkGMyMb9LAlL5jK4ls4gADXWlyugsf3bphxW3zNXSpZ7efQSDMgtW8qn4kL4kk8tvLAHX3dbLc+hbr8Nz8dRv4/aRh5VRoeqKbtN0GSte2e+St/XwpU16QzN2rsPijoZ3D7KniWnfTJxmRuZ9G3sis5NxQI/yLk+sFhHkdIaPmenSC8Fp48MVWMQaaEI53fwh6LBsfFCMWoBSsQ6cUdeSBcHTAUCA+8hAW5vOL3xyIbpdAtA7W4PjXNEuBpEzy2OMdvrfsY7LcXGhGm2T0ar70J4vEKo4L5yAQ5LdjORSXG/xCAV+gmTmepCtMpRmWH3Zh0971FCBiHzlAUSCHfQsg9AA68vhGdAWhsEtM/kNXfdsYqMtk9CD36z1Xe6BXmvnQkwoJSgw4Uh3hm8tDWHE0koqdocD5xlbJDvK0AQ9Q7+6mNAqNC2a3bSEWGRAzBeVbuVqM04joYPUkqrKoRRHGN0FM9hgH9kDGP26zBAjv+v6Q7ciQHX5BxaufRWweT7M/0yohlj5OrpbboJyCrIjYBYLIJwU+BWBeFflmYRG5GN33h/o0yzLPCfAuu/ScgzLLvGZq6wbeaKUVD+6lc0Vnk31NrAvmDxcwApy9nqVB7KtSE/vbUNCY+qwcyhjyrBttRkLxHO+d3jsFusu/nAtKWF0mvWYevazhdzKkxyi4NRrmX/"
    }
  }
}
