{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-api-token",
    "namespace": "external-dns",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-api-token",
        "namespace": "external-dns",
        "creationTimestamp": null,
        "annotations": {
          "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
          "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true",
          "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "cert-manager"
        }
      }
    },
    "encryptedData": {
      "apiKey": "AgByidzjZJNnwqtchNP40bKLhfUnCHXp2jGP6v/nPWnLkpGv8Wyg/5c1X15g6nj0zgJubfIZ+WQtqJ3i6lvlaKKWDqRB/Ynm/I8LkmNRqfhCmIXVlv14UIpeR6+zEZmXG2BaepLrD3W7GCnpfa5xVBG8MMGD0fy8CaK6zCYAzl8YMkxNHATM5kbBsu4U4THX1DyFvX/NokALL5fkj3z9x7kGCqYqbjhji392EjGOUI8Abew7NaMmdHZgEf7lzwzs6hzTaQbutp3dYRMSObY2ah3YNa1CnGHP629SnQmC1tvUELkEiPHvWjl8/C5kdcMF7hxxZW7sXjGZpNYf8NPae3p1LrIY2+Wue0uHxRwo+Su2b40dA1r+wnbD5sCBopL+7FOujDFQwnM/2fneY5mONi5qbyqfsEJi8sTS6HcIylIqsJUUM9mzGoPpBt2ljx8tqPp9L/SZ16Tul5LuKQCutu4KazSctshkc46BVdoeBD0r7xqnUUSNQmfOp/SgOj4y10rLiNdLSolgg0Lj4+jXrwwf1IFK9BY5NUWSmNz0gxqaM8X8wpn5IDgwdtO3YvuetWsolIx+xy4t+oY+OVPD0ZAcibfEMiQyjopy+tEbQ6lHk2qIEWWaKEDWtY6viQiy1ZGkWLkbgV5fQtG26Yct6nhGWuztX8e1Z4qqd4+C/oYl/8St6svLnEj6YV69Cmz6EWRrV42Fe2S6tGTHwPHiz+0BrpRWqYymvpvt/iu5Ewq/YVzdILhD5C9z"
    }
  }
}
