apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  releaseName: external-dns
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: external-dns
      version: "8.3.7"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    sources:
      # - crd # TBD what's better
      - service
      - ingress
    provider: cloudflare
    cloudflare:
      # apiToken: CF_API_TOKEN
      apiKey: CF_API_KEY
      email: benisekj@gmail.com # maybe as a secret?
    policy: sync
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns-cloudflare-token
            key: apiToken
      - name: CF_API_KEY
        valueFrom:
          secretKeyRef:
            name: external-dns-cloudflare-key
            key: apiToken