{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-api-token",
    "namespace": "cert-manager",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-api-token",
        "namespace": "cert-manager",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "cloudflare_api_token": "AgCQI6yGTDP2QMrIuue9HPzA/RcdGgwaDvartErwBrg+btCuDcVCaajm+R9fAkRHUggKf88L8O8Ipnk8XkWThtChfufFxwHMuSgsXjQss/YeOwnBwFawOo3Sh24aUWNC5k1pdJhUN4kxhUJvTkFutc2tkZ+o4QeuUt+WSM2DtvYMyFFMB2BXdjTRu2vVty1YFCc9MiBy9bRjKPkv3+SY3LZjWroPj1HiM2B4WPV2JMvkG3WjNxqPjxsJhVgev+ulAWxVD5PlxqrH3Aj2K0SqKWrqHR1D22qxvyZk9XPHiWbKx6VWwcQ4jyAbcxjOVrALdM696saeyOjICy4OXKquQvqKFc8Lr8WybEqlE/sMmeF+b7X7sruvtodQ56S7ncg9YNX+xqRXXIoP4T5Z/0auiV1EspEAJywnykdFHDRPouvFa3BGkYKttnt1RZU5maVgOoTPlu9fQHJnyIQ+YSZQ36nXpROmftLVYqHm/ihcr0Qe1NqdWN9zOfssuKqGzSxheuTR0cxcFfQeKgNwlS8cUaApqvkpPU3qncGEaWAfE/X1I12RfO/gs0OGVBOr7CCKUiRjVxBZuGdPdx5MZi+icI2Lx/m5pn2WoNlzld81axjBT5CIreD6c36Tu/2SUGu1JSlDKfCXbuPVxB40/3xwxaGqOeJcdUWLElvUlun/aSUo0nBwbBYyvUn/9gAjay8oXs0Nm5J8zpCAj/Sc5fsIdW8N3U78ykmh7Z6Sz067bL9HkQSzQFOTHSNM"
    }
  }
}
