apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: funnaiest
  namespace: funnaiest
spec:
  entryPoints:
    - web # needs both
    - websecure
  routes:
  - match: Host(`funnaiest.com`)
    kind: Rule
    services:
      - name: funnaiest
        port: 9090
  tls:
    secretName: letsencrypt-funnaiest-com
