kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-immich
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-wave: "30"
    k8up.io/backup: "true"
spec:
  storageClassName: synology-storage-photos
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-immich
