kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-immich
  namespace: immich
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  storageClassName: synology-storage-photos
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-immich # this is static definition, dynamic creates PV automatically, which seems recommended
