apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: collabora
  namespace: collabora
spec:
  interval: 30m
  chart:
    spec:
      chart: collabora-online
      version: "1.1.41"
      sourceRef:
        kind: HelmRepository
        name: collabora
        namespace: collabora
      interval: 12h
  values:
    # here
    image:
      repository: collabora/code
      pullPolicy: Always
      # Overrides the image tag whose default is the chart appVersion.
      tag: "25.04.3.1.1"

    collabora:
      password: examplepass
      username: admin

    replicaCount: 1

    ingress:
      enabled: true
      className: "nginx"
      annotations:
          kubernetes.io/ingress.class: "nginx"
          nginx.ingress.kubernetes.io/upstream-hash-by: "$arg_WOPISrc"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
      hosts:
          - host: "collabora.${DOMAIN_NAME}"
            paths:
            - path: /
            pathType: ImplementationSpecific
      tls:
        - secretName: letsencrypt-wildcard-cert-pengiuns.com-production
          hosts:
            - "collabora.${DOMAIN_NAME}"

    autoscaling:
      enabled: false

    resources:
      limits:
          cpu: "1800m"
          memory: "2000Mi"
      requests:
          cpu: "500m"
          memory: "2000Mi"

    prometheus:
      servicemonitor:
          enabled: true
          labels:
            release: "kube-prometheus-stack"
      rules:
          enabled: true # will deploy alert rules
          additionalLabels:
            release: "kube-prometheus-stack"
    grafana:
      dashboards:
          enabled: true # will deploy default dashboards
        