apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    argocd.argoproj.io/sync-wave: "40"
  name: synology-storage-temp
provisioner: csi.san.synology.com
parameters:
  fsType: 'ext4'
  dsm: '192.168.178.96'
  location: 'temp'
reclaimPolicy: Delete
allowVolumeExpansion: true