apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  name: syno-storage-retain
provisioner: csi.san.synology.com
parameters:
  fsType: 'ext4'
  dsm: '192.168.178.96'
  location: '/volume1'
reclaimPolicy: Retain
allowVolumeExpansion: true