# TODO: Figure out later, might need extra permissions on Talos
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: syno-storage-nfx
# provisioner: csi.san.synology.com
# parameters:
#   protocol: "nfs"
#   dsm: "192.168.178.96"
#   location: '/volume1/nas'
#   mountPermissions: '0755'
# mountOptions:
#   - nfsvers=4.1
# reclaimPolicy: Delete # TBD
# allowVolumeExpansion: true