apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
    argocd.argoproj.io/sync-wave: "40"
  name: synology-storage-configs
provisioner: csi.san.synology.com
parameters:
  fsType: 'ext4'
  dsm: '192.168.178.96'
  location: 'configs'
reclaimPolicy: Retain # kept afrer removing PVC, must manually delete LUNs 
allowVolumeExpansion: true