apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.178.2-192.168.178.250
    # - 172.20.0.120-172.20.0.130
    # - 192.168.178.0/24
    # - 192.168.32.0/24
    # - 172.20.0.0/24
    # - 172.20.0.120-172.20.0.130
    # it I don't see the range here, it will not work netstat -rn