kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-postgresql
  namespace: postgresql
spec:
  storageClassName: local-hostpath-kevin
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
