apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    pod-security.kubernetes.io/enforce: privileged #otherwise some deamons are not installed
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
