apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: loki
      version: '6.28.0'
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 1m
  values:
    loki:
      auth_enabled: false

      gateway:
        enabled: false  # otherwise rules prohibiting some nodes

      image:
        registry: docker.io
        repository: grafana/loki
        tag: 3.4.2
        pullPolicy: IfNotPresent

      commonConfig:
        replication_factor: 1

      pattern_ingester:
          enabled: true

      limits_config:
        ingestion_rate_mb: 3
        ingestion_burst_size_mb: 15
        allow_structured_metadata: false
        volume_enabled: true
      
      ruler:
        enable_api: true

      storage:
        type: filesystem

      schemaConfig:
        configs:
          - from: "2022-06-01"
            store: boltdb-shipper #tsdb is probably better
            object_store: filesystem
            schema: v11
            index:
              prefix: index_
              period: 24h
          
    deploymentMode: SingleBinary

    singleBinary:
      replicas: 1
      persistence:
        enabled: false
      affinity: {} # otherwise rules prohibiting some nodes

    # Zero out replica counts of other deployment modes
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0

    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0