kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-media
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  storageClassName: synology-storage-media
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti # Just a logical limit, can write more, current max limit is 3.6Ti
