kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-media
  namespace: media
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  storageClassName: synology-storage-media
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
