apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vllm-stack-opt125m
  # labels:
  #   model: "opt125m"
  #   environment: "prod"
  #   release: "prod"
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce  
  storageClassName: local-hostpath-kevin
  persistentVolumeReclaimPolicy: Delete  
  volumeMode: Filesystem  
  hostPath:
    path: "/var/mnt/storage/vllm" 

