# Needed to pass db credentials as secrets
apiVersion: k8up.io/v1
kind: PodConfig
metadata:
  name: backup-env-config-immich-db
  namespace: cnpg
  annotations:
    k8up.io/backupcommand: sh -c 'PGDATABASE=immich PGHOST=cnpg-rw pg_dump --clean'
    k8up.io/file-extension: .sql
spec:
  template:
    spec:
      containers:
        - name: backup # can be anything
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: bot-immich-pswd
                  key: password
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: bot-immich-pswd
                  key: username
          securityContext:
            allowPrivilegeEscalation: true
