global:
  checkNewVersion: false
  sendAnonymousUsage: false

deployment:
  replicas: 1

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  traefik:
    address: ":9000"   # Dashboard entrypoint

log:
  level: INFO
  filePath: "/traefik.log"
  format: json

accessLog:
  enabled: true
  format: json
  filePath: "/traefik-access.log"

resources:
  requests:
    memory: "256Mi"
    cpu: "10m"

service:
  type: LoadBalancer
  ports:
    web:
      port: 80
    websecure:
      port: 443
    traefik:   
      port: 9000

api:
  dashboard: true
  insecure: false

dashboard:
  enabled: true
  ingress:
    enabled: true
    className: traefik
    annotations:
      kubernetes.io/ingress.class: traefik
      # traefik.ingress.kubernetes.io/auth-type: basic
      # traefik.ingress.kubernetes.io/auth-secret: traefik-dashboard-auth
      # traefik.ingress.kubernetes.io/auth-realm: "Traefik Dashboard"
    hosts:
      - host: traefik.pengiuns.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: letsencrypt-wildcard-cert-pengiuns.com-production
        hosts:
          - traefik.pengiuns.com
