apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vllm-stack
resources:
  - pv.yaml
  # - pvc.yaml # don't use, helm chart creates it
  - namespace.yaml
  - repository.yaml
  - release.yaml
# I am not able to deploy this, the pod does not start and the PVC is not bound.
# I suspect the pod cannot start because I have no GPU?
  
