kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vllm-stack-opt125m-storage-claim
  namespace: vllm-stack
  labels:
    model: "opt125m"
    environment: "prod"
    release: "prod"
spec:
  storageClassName: local-hostpath-kevin
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
