{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "hetzner-credentials",
    "namespace": "k8up",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "hetzner-credentials",
        "namespace": "k8up",
        "creationTimestamp": null,
        "annotations": {
          "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
          "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true",
          "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "immich,cnpg"
        }
      },
      "data": null
    },
    "encryptedData": {
      "password": "AgAHUfv+AMgfPratoMxPpOfVp5kDWABXh/4998V+PgRYCNYMq9fMiU7m9Zp6AXKAjEpdYxL5vEY7mxfwPZt2c9Lg4wgEdm0pIyruKyXQwIq0AkLCfhmX1PThH6c1sMpYgA7IO0ARC2x5i9JR6Epz1LDS11HN0D0YWhcka8RXb7hIqCqC2i+QYPiDj3MeBEfNoESLgyilw2ovYM9JXzE9Jp+Gzp3lgT/DSSJvm2kiojZHOOyhbIWc3vq2i2J6SKWW2DWJrycl5PkuZN+/B6j3Iodo1OoZ77n5drMP/JWttwFKWtEM5mJ5f6gwW7MNW2gQnFyH+Lbf64TM/yV/+oqpmkdlezFrOxVMoYaYKxSL7L8OIpb8VmStzRZBXcu4HvxA1EI1NKzBM6dMzliE8fW6wLMqC3IdVh1kZhE5riFmEIaJ4yXrzPvjnO040Mud4vl25iUdLYE1+Q3hAbtwzmWiBrAkTnMIrsXc2mx+kv3XpTg+b710gzhC7D5zkLmxz4oqaRMub9QKV9Q0pkRCJOOCuA8JuZ8U8CZ4CJSw7NF9aLtnM9C9866QOUHKQaDKjExtAkvKoHWNeBIqzDoiARE+iVorMZdU77WA28ZG719Z8qWSdxS7rwBckxU4TT4ii1vOrGhPX4LN/gwwX9ZhcAXYxD7oarmmHh5MQYBJ7On9hxG+0Y49QmuILMS4S5sYOXb3JT15Z+aCl1jiiXZfO2p2ipFP6XOQOg==",
      "user": "AgCIb8V1k6K6QHD1cprmCbof5RtTtmZeRMOX+NFkFk6X/+zxn0UmEUY2v7ePjq/D1mhQojjvrs16S+aFIKEW7b/AlMZPvJlnjLU5XLKYqP8sGA4rJrSO0e3BfNHZslzYkYtFl5UteVjSwFBuqShe+97pE82ZE0DbDaEOqX2dP8W/jVOtugXhK+6wkvgbytd4gg3TS0AGoisFEX88gNxu+1ryZ6dVmINUfwSF0a5jKdaSUkwM/NgQVKrVA7bA3aMNxDhu9Xfr4rw3Wa8jGKesNwLwfgSL2Vp57gJOgQ6fo4PJWfhWM0+F9eYuDK/tBFxhaYgKy6y3eBYWa0SPlAbsmtWkjwbBvb8PqASOUpGeJXx3xAG0yQuQmcr5hgd3hP0WC2ZfKGU038ids5byQP0hSqoz4Pg/TgauhgoJhKsXOTdWIX5s2b6c6jglOYFOYWi+JmHlXMrxFgSGYseRkk0Md20H64r24r0E72nR6pPQxPLjJD7NPPL6Z9zAoWnPPlHLG+xSi8478hCQ3ebSXaNC/2aMDH3bnSXZd/u53Jshhql/XZYdVt/IZEK4Hgkpw+vyh64dSoeVAN6f9gcTsqBMrggIL8wS6aV6EeY5KY1qhEz6lK83v3hTfPfwEpdsNt8mtlH5mj4eMbki7Ba3ZtVH3yiKZXRR/mWO68HuUNeVw/tpJlAEcl5jgL838+mzJE3XAuAb8OnEtJxS"
    }
  }
}
