{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "hetzner-credentials",
    "namespace": "k8up",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "hetzner-credentials",
        "namespace": "k8up",
        "creationTimestamp": null,
        "annotations": {
          "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
          "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true",
          "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "immich,cnpg"
        }
      },
      "data": null
    },
    "encryptedData": {
      "password": "AgAgjViNk4b9wcv0+Np1unJScof5J6pxABQ80zq3uyNCzgz9MQBUCVEB4HJtfmrIqFFhuSb5nrHumVxxZ2Yfr9ysdLcMrKJpbrWcgc/7pPIyXq2eU61NrkWuhc91rNTIt+Rc+3ZDu+ZR3eQmgVTTWEqyX1J1I9ReoKGBO8ii5Cxw7hB3sZpwBDTrhWf3p8USV/OIwTCMOb5/Q/yu+QWBqbZAn/rAy5oZucA4fWABurZju4NpR6AMc6wNbPfWfQlPf/QVW8/0cIthe4btXVQs/4ziSg/63KcHz7vuW4em6rwHbwBBba5/CaCXtIJb59s3cjVJpE3vUQlt2730Q8MVJm4Q5d0XHZUOUE+o4pm4dBjEUnKB+azBV5mZcDsFRkF7RUu+UeBdE2IFhoyC2Y/mBSCk0/8T/p2AYJXtmIgV3R52ISY+pGoInHp4K61mbwGNssGZJc6TbedaUWWuF2ocD5bUAiQN7p9NtD+Y2gTbbsNBKjZIkhnv6hRjX7aKwLUguNu/peQIDiRsm5WipxMoOzfN/VPPmxA1pIpwakyaQx4XwIK+po11DcmIWatsU2xCKyMlLOMw0Bc2UdH1yi9KmCEQWu2/f//v9l0URQXhW1A3tUO5Fd7qZrz5hg/Qks0KdoLriH5rE7GYco4r6kUXgMmeGQjgsHb03/M9Uc8llZZGt2uQ2gbq7HsK8Ie8AI/zOnSHYzYsYs+SFNKJbg1Qyqv9j7nobA==",
      "user": "AgBqVZM/yb7bk8NkSsjtcjDkBqBzo9LpPk+U7yd951E0iuI5zw6zQd6MIqqW8aI68Yl3mjubvOsrxwYCfCHOJxMDRJT0R+rXN/uNYcKLga1tCiM5CPy75DvsUZua9roMOT3DNfPJ8N+Bk7jCgMliRU0TapGi+0J+JOXjOkKZAWV8dYnz11NBA6QbzTyfZZWHYiLfxrO7WwUh1P2niOSrnWCDN5qjzH3KszYFzFuxqfVixSYsoVlqmYDPvFKaPaAAp1SJgSDC1U4PmQOLqg3YjzDOvraMSi6SeZh+uT/gsQu3YxexW5Py6ZEUVSIErHIPGX3LFLfBVgVBbbKdG9qyaZ53jKmVZwyAHwzPSz5lU9lIrG1dU9nvpwhx6z/3DSC4sIyxGupdUA+ZjiwmqGBPTFqpp2PMXTJikAEoOFye6Ro92iA/5fN/GR0gi67h+vknIqRWcGNwcQtqGRvrOXMDghFkX/gbHHfrdRKqxX4D8f+RgNd2WWUIkUBwLng3F6VM5l4s3lEfmnrvGKuXCfKyaEaXbb+p7Xs5frZc0VW5oQSiXqRr/RpbkX1siGv08XLDNv7Z2K4Nnoz2tRzs/3QAvcTZEtwKynN9QMQmuqWzVEagTv4wWvCarpzdgyvBLUMEAGXbY7FWXqIpm+4PI24uATmmDGfPjzOWQlSutuhdMK9SeTozTu2ICvyZ1XIFCLwKQvkJpnpthNc1v3j1rN0MomxNapHfV771zwPNpEdTXCOSeUiADN8+BaIH"
    }
  }
}
