{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "hetzner-credentials",
    "namespace": "k8up",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "hetzner-credentials",
        "namespace": "k8up",
        "creationTimestamp": null,
        "annotations": {
          "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
          "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true",
          "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "immich,cnpg,pocket-id,media,otterwiki,jupyterhub"
        }
      },
      "data": null
    },
    "encryptedData": {
      "password": "AgAFejnkzzF0XW3TWv6NZ6Xte4Lpn7zj8kvB68VxiGnaR43UcbT866d+t0Z3cCn9Bu/oj+c+IkTblqkWUGSh7ONK4t3UmjBFrKcVNuPuVWJ+SAMlWL/XCtwH/Z59nLiy7wvXIf62n+oDVDNsH3r6W1z/Gy4xfZJUjSEESyH6HheoDah/5PcR7sbasOMFDbhpTIkhBDS3T5CIP1UoVvIMuaSLdIYlqH6W6hEgnoXRF7pbRROC/61ayNiAPuhLcIevyn1TVPybN1228pxijFrDHZOCxoncKjXfhWL0rDy7yZXUyuA0zlZ6jpMrJjpLZhoTb95RW63INbk44lkx3l6aF4LmLzXvgbu0rcWnyJk75fALvQUs5gtBwJlsYau4Ez7lht27dM5rM1ZxYhJHjkOKJDnN7q2X6TX11Z01MFZwK5kql52ibry6eFyD4FoLuUbZyrGwd4SLUde/LzrTDm6z5Mu2G3Z2+eBmWTKc4tH2CE1NgMbDIruoxTxCYPlGtozFuSAsJo/kZ1GS67YSPrKiyeoH5aaGUkg6x+6m0y9q0/TmKl/EohmzdHiL5vyESp5ECB2zusi18gkLVbidDnzBYn3TaLceGNOavQZ6qksKpdIr6ZX31kJFn0uKbl1ZfjG2qOISJynhP9I7BQNjxU8rdLkpDtkHS4q2rZ8legOelTemNrD1t7yJb7+jURzVqqAnM+oSu+97fQzXy9Qv9Pp0Y/xQEOPjY1KX8ertIy/hzsV+VUyOFzI4YvEj",
      "user": "AgAyfylok3aqyknpPFC86LOBhTSnr0z5GBYvoG9r25dfkLnbqkOCPo2FXkVS7REAB+3QLr79h3CTCp/60m65OiOZ3HWwVpDgCspmoip3bVN1yY6xbYIwNnvWRakWae1NGePQnneJyzNqDzSH3tBfM2RrEQcN55MMWslpKAFGT1zyur8juPSR1550CqNiC+aoX5BYl6bklNlToJLGm19mUjQljJMMGbowV0xpG2rB+Toe14WdwlOLbRfiw74Lq1OJOgZMTibFhNsYUXSyXr27+n6Phk49DlQxCY1zq81y2sQwnNyTdaaTOZU0UwzSpIcHVB8XQ63DBDD92jVbQb9QKLfnA0sPEdZjFPjN6YLgSUjMshdjxQJuLKdsMAT4sBOIqj9ibzTbaWXuSHWKyvOuzrTcrtotGFoEgwoffU/eZvDzkoBglJ3p6shrhiDtk3wviriFyVrw5BiNhJpdyxL0nRduCpCmPQTw6SPYy1WyXlHdFN9ZG02PWOC3EsBirRlHCdEMxKOsoQ9UWuzinqK5+Ro33AwKhsK78LKXrMbm38WRoVxmHkbI59T6ESVixHNad0eHwlAaA5/ueW/tRqgOGJHSBlr4KKa5Oe7pNcc9Uf2ulNnF1DfSNnJE7/Jygibr29/XscNl4R8yfP5yUywird8hSuC/SDo4iuFEK2RZr84FjmmZcZWmEMynBGCwqtFo6msgbA4oYnobLjx//TBT4Yg5CTbUyQ=="
    }
  }
}
