{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "restic-credentials",
    "namespace": "k8up",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "restic-credentials",
        "namespace": "k8up",
        "creationTimestamp": null,
        "annotations": {
          "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
          "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true",
          "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "immich,cnpg,pocket-id,media,otterwiki,jupyterhub"
        }
      },
      "data": null
    },
    "encryptedData": {
      "password": "AgBJeZ57ynPNj+1hFc2fEkstGyFzYISSy58GmTQ9Q2pOwH6pCGA/NneD5blxBeYdl4ztgcLscGlh/biQ3DE7oIeczS7FPDrfE3HDo7OBmYuN/DqXAnrmMoiDVPd5qdAu2lP7Zlg70mVH+gNK1GA/KPVNYJqVAOvM5EYj/fmvtI757XK4H04oNd8AGNL6Yqb7gDaIxc9cQMueX9Co0TWSFhXTX8Rgdlpzg/g/b/yd+jO1JFt5b3CgAHXBVUmt6YeqK/3h0nRyZBY9U28MiTEtGi6eoBq0nFqQQuS8Jdpe/A+x2vL8iU8D8uQF72yZRi2fKMxv8USt8uAiZ50bU6McZNRWn7q1+SW9GJgX7CQhLOPr3zaRI2VvJV61/mygBwwc/yKijXeYWiJ0obuRpdXktRQkIFLS7pKLqpyNq8jrBAQ0Lef/dHgSsBMrH9aN59zmOEggdmJGU9mssT/o7AWI/IEuMHs24NAPgrdX244tknvJEcouWtDcijz0+j5RDExwgfqdyqWXmawQcFT9JAw70+0Eda/HwKJ5fI5nI0NJT0hS3XJI0y8onZN5ueM7ChGSg14IO8tcyQos5CuY7xulkgLgq5BWh56c4eXCSp4EpvLP6fot2EWE3XtnpqJISoStTMU1yrd/IH1pbkHOy2gzqQDJO43HImECZ/+R1ZOqKngykcushwnYgw2XhX+VrWJ+M7cwtrpjHSm96B7b93GpqBEelif6CUES2yOIeUY3xK8+ee1lsbNVV7f9KzeGJw=="
    }
  }
}
