replicaCount: 1
image:
  # -- Operator image pull policy
  pullPolicy: IfNotPresent
  # -- Operator image registry
  registry: ghcr.io
  # -- Operator image repository
  repository: k8up-io/k8up
  # -- Operator image tag (version)
  tag: v2.12.0

k8up:
  # https://docs.k8up.io/k8up/2.12/references/operator-config-reference.html
  # https://docs.k8up.io/k8up/2.12/how-tos/manage-pod-resources.html
  backupSkipWithoutAnnotation: true
  timezone: "Europe/Zurich"

  globalResources:
    requests:
      # -- Global CPU resource requests applied to jobs. See [supported units][resource-units].
      cpu: "50m"
      # -- Global Memory resource requests applied to jobs. See [supported units][resource-units].
      memory: "1Gi"
    limits:
      # -- Global CPU resource limit applied to jobs. See [supported units][resource-units].
      cpu: "500m"
      # -- Global Memory resource limit applied to jobs. See [supported units][resource-units].
      memory: "3Gi"