{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "client-info-secret",
    "namespace": "synology-csi"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "client-info-secret",
        "namespace": "synology-csi"
      }
    },
    "encryptedData": {
      "client-info.yml": "AgBbiNSo9NG1zqitYfS6+1adBJy7XnEWBDZWzV9J1reYeNZJ0nzDfRx2CmiW9nuv6XLw7QuyGG7Q/zkrGOuX/2o19HF5pgB5AhWvrAlyKVCvj0TY5aPLpwzhYgMo2zh96T7AwuWtPqlWiHau50wJkrbJi+LZ//1GDMAslnKZvABxA/74uUv0a2aaeNBdIi2u7Xh/gjp1KbQ++EV0Ak10QkLibhdxjZEudnNUaySoPCg6Fs5jchQLOm53NT2cH45tE4xAKHd/DOvL5ZvUFR9sW/js7kkjAADvfhbuDfucMEbMd/as7urBl8jY12XNZhju/3OL0U/S7r/pgpKV+xiLwzaTvaVki8fqJvS6ghswwyWryj9Vyfnk+QwK5AY6W2PV/UXcuTzdcUJ+u314BNJ9/tAStOuK7DC/F2ncZH3BzLFRq9YpeVEHJihTmwqBcTBKLlOtXsFPo2dD/9BOfZRBh7cTelOSvKtJMPddnST1ogr5Ce07uDtycifZMY/G+43jewdyHxWmctgIFvJS23+dYbL621K/2UBs6W0AOIrxEtBznbbosxbEcepmkryUZM4lEI5u7sZbvOtnILWG9ADZXzkNzDfXtiucrA6cLnDVhLNMZ/o3qoRBY0aOgxEw/3/mMoqQapkMaHSw4QCjNoEDSY2D0zAZKsUguv3EhRF8dnBLCBp+oxK5bF4o4c/tVdiqZlpdfK/SHBLeJ7q0a8JDoqkPalofTJqzLpi78qtVGQux8Me08Qsf7gTxmNB5blitCNXbG1ihswaOwDXC9q+kxJWq90APlPEjSK/vsT+5eLOEPFhQoB21fuFVX4ZEJNTTpQ=="
    }
  }
}
