{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "client-info-secret",
    "namespace": "synology-csi",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "client-info-secret",
        "namespace": "synology-csi",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "client-info.yaml": "AgALwoVnlxIKviiZ69ya+tB8+xj/CBKf2PMhTyolHw21vDJDhOY0Mvfu18sSQsfihwuuNmxi7jq1lJLXwrH5ekOHu4ACc1Ha6LlSfC3HWN5BWWQ2sTblaCxWubD7igIHhbZU+itDhKUjyzC8WfoMkXQo1PVlUufGfbnY7kTiKO+0STijZRgY3WuhiyMStx7AecevsTPUFswPSuei/MfbG/cYC/XJV3YVD7wym/tcD6MyZrF80DL0oA21F0DX3DvRFya89DMj4VLJvXS6QE0ktv94A67m4lTql/x7p48H+s71BojpVF5JBiAgHVzQp47LtY73IeN4ZQHcpAbiYuROr+R8ZshEPyEKy5m8w76HTtIrxsvlUg++MTFBczxLuWHVH/j1gXlylZH3sENTMTME1eYPbgBZSWjt4AbWYDwHONWqr3/BELM0+DUsPNoNs2rR3LdafpOeE0LXSIbCjtJl/sZTiqOTqdWs3y5LS/r9WaWf4IiZ8uV63avajmZ39TT/dkhNb/gG96QO0I+gZEsC51ok4uuZDkU1BYXvntwI4kdcpVBzqFWRMEfstr5otk33l+imjpXvgNsypNyF6KJzV5Qn0opjCe3IxbHUzukcuqg5/CbFhAtU8lvkOsWptOmjX3vg0uZpdgJ/QjdM460IfwefmjKaMnFnymOroex0Z4jKhhyC+iTZIDJwBeI8AQqI2eWxkHqIe/7nayHgDtRPkYXSSjIwCEguJoWefP7i8bP6GP0qHgdgUEhUpuFq7MhrRzJfwFLInUkJhM6QsI+hk95VEGoVb6G2+I05geOPmHPJjbkVq0Lpv2huH6ceqKnnsHklSLQ7OMklJYhKayAn3OZSAHrSqgvP42n0LFKSiDib0EddjLTvj0l2V9ifPbB9VOdLTjOQxbW/90F8wVJd3HyNaym/J7L4zFnFKjV0PVNMV2A+LtXeYfNdEgPEiqj53j0LGrx2WD2w8tndBAt3eNzb1VLhxd1L+NZurKgM+Ij16b6NeMbQdYUZ0J97YLeSyk/hYBdhndC/850UXwjK90ZPGARgJnFI1nhmrFFlxvc7DpBk1yyFZNMCNzW2CA5SNHZplRa11TtdkxeKX+Npbj+T"
    }
  }
}
