{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "client-info-secret",
    "namespace": "synology-csi"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "client-info-secret",
        "namespace": "synology-csi"
      }
    },
    "encryptedData": {
      "client-info.yml": "AgAkDndMPfMH/S6K2Ydu9yOmG4rRgEzi0zkXXrZFQz2hjRspVuq8NQuu3I63mRqbExrTy93YX6Ug+xaTC+HMyTaWyK08076eAWFxtZ93znGvGpSnMvggf/V2hw63FBb39uunuJ/aZz2X5ditfHh/b1pUX7cvgD/oReAy1K7Up23qoJ4WscGus7iE2X9GS5I/mDJNF1pafBzhjWiKv5BoH8UX1tAC+npcHCMaVnSyQw0RUzmhrtSoWkvk6IZMtakdcC8MyVrNlvpdpLZREBLdjgCa99nvmlj3U5xHzj0LIFTQcou4Hk8VM8T1bB4LGMm9Ml7VReP1QPG3pTzjeFDmxgvI2BBI493VhtkGAaIBpnKvpVYDfTea8+3u30mZopJw99l0Dmjmv+Voszaein1epPVVrtugS1C/nuShlPxLg/5j/svgx7/LA1QVtDHd9RmrZ321pGwDn9W8NlTTx9EDC8+68PYdCN2fOo5pin0oUwPIcuaQFoi7lD3YUmmzlPy6cr9uBUZCuJvAPNOUmKWMM9HhWiXvFoeoFgf79qPNXnGSUSwHFuRpVU6x+wrWHGA24fz3mGwRbltW8U2zGUVfNCiY+6U7MZXVFGONCgAtSoRY3lrMeDBJ9NCBPexN7d3kWWOWX1jFkXxoYura25ZKjUujP/Bz8TjeVqeHroOBhTepWKh2DKEhzrC+GLBPXh1fMIELhCipPTSqzeZo4Z2weO4Li9ELhn/8JSeOPMsAEwJj1DhAvGDfbfQr57C8NBTeeTaEhsMQxAFSOX7H6ul3yHL1U35Vmzw3K1vvegovMJ51dcgbOXh3JnhfbTdJMstOzA=="
    }
  }
}
