{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "client-info-secret",
    "namespace": "synology-csi"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "client-info-secret",
        "namespace": "synology-csi"
      }
    },
    "encryptedData": {
      "client-info.yml": "AgB/oYcFhJLN4Ztoce5i9u1WtfS75ySvfHNItBxZ58BUnnmvwyWxAXmHzh61DmyaVpLHYWWUTCVZYTCEYOXMcpqQd1PSSpyQoObV4MfHKDM/XWZ3KcvFoITs+bJ0+ID0IfU9ScVh3WxW3lV9lOugAVat7eTHwa/jvQxT5Yf2qVfYbWxr4pnVo1BRCSjw/1hbSJj3xaygiY59INL7iqz5izhqzWGLMRaUwDCj9rgJ3uwKBKBYIZLuMhs3efgMapsXrY3JSnOQO2qcBRwwxjzuCHehqf5eKzUh9cg6lATV7oVevq4eTkVoNhj656PyuolS0fKRd8BbBn7Fh9vGKXfBxHf3sNT96g0LgL6VNoGOdqNZYVwSgxjwBFyzFp4UhlRTMIsRTBxTVDhIdN+LHEFMJWrAC1feGG4+/7z2A83j9oBIlWwD9iK2MVJLFodl2OVkoDPXgILoRgjsIAM5lQ32GlO3Gesitw4iek/K4Wcb9lvnAdg+85RQ3zMVIRCm8q5MzxpNLIx5RYTVY+wlGlHTDmmqiDTXB+WFDZbYN6XQrBGd9KiLyzS6SGQuyQVEDlLSUj9UJCcEx193UoQIPEDNAMsvr2OVM52IS22mbaxl7HbPf4uKYTtG39O+bj+IXelzQoUT3pQ8dQ9CgC7mUHNTjPbQahFUUND0sZ/VVeLawfyp/6lWv9cIzSCqGf/VDEEIHStc6oNQiuKGc14fzo+d+mIw4vhwZ3rPIP+S5PXby8HCwuDiSHPQXgXQF9o83dk5onMASocpETFF2WLn+eV7nWINcNn33VzR0c49j9nAZDpU68tIoYgNA5hh/NGBQtfWwqBa/MB7htk2c+pex8+NgzQ="
    }
  }
}
