resources:
  - ingress.yaml
  - https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v3.2.2

patchesStrategicMerge:
  - patch-server-insecure.yaml
  - patch-disable-dex.yaml
  - patch-disable-dex-service.yaml