dex:
  enabled: false # disable

configs:
  params:
    server.insecure: true   # <-- This tells ArgoCD server to trust the ingress TLS termination


controller:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

server:
  ingress:
    enabled: true
    ingressClassName: traefik

    annotations:
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      external-dns.alpha.kubernetes.io/hostname: argocd.pengiuns.com

    hosts:
      - argocd.pengiuns.com

    paths:
      - /

    pathType: Prefix

    tls:
      - hosts:
          - argocd.pengiuns.com
        secretName: letsencrypt-wildcard-cert-pengiuns.com-production
