apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: emberstack
  namespace: reflector-system
spec:
  type: helm
  interval: 5m0s
  url: https://emberstack.github.io/helm-charts