{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-tunel-token",
    "namespace": "cloudflare",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-tunel-token",
        "namespace": "cloudflare",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "cloudflare-tunel-token": "AgCIkqwMXFOUITG2cIuu4J/5EtO442geiIIPghRjEWDMVz4plvqGP9qF4Xfmm6+9pgdEfnlZvLgsREgQbclS7pmUtgHeqzDaks7fVGowSj9biuEmVBJPPJhBNIkwBHqVlZkwt7uMl3OF1UFgnrPww4WWuj+HD476Sb0kqEcj+8bxv9PmAaU93z0CtSCxIVdh8u2p83bNd4U6f9c/CFGQlpgTQTJSxmsB5GEkzVdY1W48N+eOhx7EVN16RdL4WFJGmTTIX2AHIEdbeRnFn1qzFuYGKnprud5xBnfcFkSnD5W4R41r2OAZOSTYNjWlW3xumgZJ/K0ox3f9FebERIPTlZdu1E2kwhKgJLUxzj/OVEVz0daxa8HGLlt7hMQNpCZ0lTOLe4wuq3gMtXXIbrBYKFNrwUxF3V0YNdfq1DFUs1oF27v26QIxTsWwVVhgAnscI0qaKy1fFkknsUOYWT4FmXEpltSgHEjXVzaoZaSkSEeMBVtqJ6IysLUxWHCkT/UWWLj0tB4n3+XVc4cmImkRREoaM1oD8DZDtfzaooVf0p+dnHrAIilOCIQ3iU7LNdOJCSbSNjyuw1B4d4vq38/OkY9lxe34UzmIU0zKpa/5k2zqIRQJsFhXEufOROmbcMMl25eLm300TdazdKInD6Bt450IhBCogqVFc5xCuNYeUKx1wnMsKUT9AKMbryGE7/bR0M14H8TMgUABW15NtmqSrUJveKTYK0mFNBTNx2XSNmoZ9Gga9XNE0iTGUzJAOt1OSjzW5E4h9t2amULbGEJnXaWLHO8nkLX2igfwz89+403mOf0gjjjCoRfL8+EHAY2Mg16gPsKkEDShvFoc7RRrKCkGoVx74VV1lOkKcxe9Gu/H1FCP5DEowQ1Nxo8Kc6XeDGBAheeRQPbAn6TAWEJUF2t+nVDNVd4uoBfaSd/vVFHYFRwZMPGAhW3W"
    }
  }
}
