{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-cloudflare-tunnel-remote",
    "namespace": "cloudflare",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-cloudflare-tunnel-remote",
        "namespace": "cloudflare",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "tunnelToken": "AgCCLK+Aj6ARsBk/Xi+adH/rP8mo0v/D36z8A5mCNH7Khb2zbedXi56T1V5wqcHkS429xScv0lo41L01Pnh8wH2rKR2kvx285kWPTKW5jeCdA2J0zfMXL2du55n8KG+Z+h8TJLFV9NsIhOS+OZ+suvkaIaPfCKtHtWASEtjPPYbkHQOlqYo3D1S/ugRcxx3xzQSqdttKS5piHahglqMynUrfwBQl5A34UEcP4uo6fzLSv8qkTOPtHm2HPllyL+fDDZ756c5mQwVv/biBkMQF7DO4KYamclR0LFa3VysiE1/vliZYT0uhD/J+HD73sGMMzcaX6RhC2iS1HRH3S0jjxOYqGH+cgdMugZOAjoZ1/no23yDdPF2eBSOQiszWDO0WUZaLAaeZTCEJSo0R6QEvqQfCVRb4apgroKPKhRQLnZtKOUQhHB7pw4/AgJuRL37NLiku6RZrfj3HYtdNGLX7s32gO49FdzJAVfTIU8uxsFWsA/1UFs2eYdnBWlrBLDZ68b7Brfh3g6h/N7jk8ZPww9O/fBl0aca+3vVNiZ8+S5g7vUZiWOsS0pc+Wpw3BzQGxvarTrVZieag+VnDRv6/9SSaTjNhZTGURNs5MdIQ/igoL2w0MgK+x4tKFzej9GTzakhmwK3/J5U5OYZD8sc5XTPbBFYE21epPt39SycnW20IEc6mdKsohsxeIDNy7v/naVv1tlfot4nYF2kg+e245ZXFZKdFNjiB3vtc2WQDVYjiWFOv8PSGOmh3m14wYw7cYe6X/ac3NT1Cr9+JdzE3dTo4An4itLtQ2pI92kxewg1Fcy2WL4W4I2rQoB5YpcIOMMvJmqtrtp6jQj5IKpsgbcOWJK79Oc+kg77nefrq2COTMgZgbOHCnUKyMtN0QotUoyoNMtCvG1BRE2KnmtbW7z89/Xu7xKRRN47luSZ5CMPaBFY08JykAMmF"
    }
  }
}
