# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: metallb-system
---
# How to establish session with routers
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: metallb-bgppeer
  namespace: metallb-system
spec:
  myASN: 64500 # MetalLB AS number
  peerASN: 64501 # router AS number
  peerAddress: 192.168.33.2 # has to be unique?
---
# MetalLB needs to assing IP addresses to the services, we do that via this file
# these IPs should not be used elsewhere
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.32.0/24 # From 192.168.32.1 to 192.168.32.254
---
# MetalLB needs to advertise 
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: metallb-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - metallb-pool # Using the addresses we defined 