---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
# MetalLB needs to advertise 
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: metallb-advertisment
  namespace: metallb-system
spec:
  ipAddressPools:
  - metallb-pool # Using the addresses we defined 
  aggregationLength: 32 # No aggregation of IPs, individual IPs are advertised
  localPref: 100 # default, local preference for advertised routes
  communities:
  - 65535:65282 # community attributes ???
---
# How to establish session with routers
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: bgppeer
  namespace: metallb-system
spec:
  myASN: 64500 # MetalLB AS number
  peerASN: 64501 # router AS number
  peerAddress: 192.168.178.1 # my router IP
---
# MetalLB needs to assing IP addresses to the services, we do that via this file
# these IPs should not be used elsewhere
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.32.0/24 # From 192.168.32.1 to 192.168.32.254

