kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-docker-registry
  namespace: docker-registry
spec:
  storageClassName: synology-storage-apps
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
