apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-pool
  namespace: metallb
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  addresses:
    - 192.168.178.100-192.168.178.250
    # FYI it I don't see the range in `netstat -rn``, it will not work
    # must be in my DHCP range which is 192.168.178.
