kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-harbor
  namespace: harbor
spec:
  storageClassName: local-hostpath-kevin
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi