kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-vllm-stack
  namespace: hiker
spec:
  storageClassName: local-hostpath-kevin
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
