# patches/pod-security.yaml
# https://openebs.io/docs/Solutioning/openebs-on-kubernetes-platforms/talos#pod-security
- op: add
  path: /cluster/apiServer/admissionControl
  value:
    - name: PodSecurity
      configuration:
        apiVersion: pod-security.admission.config.k8s.io/v1beta1
        kind: PodSecurityConfiguration
        exemptions:
          namespaces:
            - mayastor