{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "jupyterhub-pocketid-client-secret",
    "namespace": "jupyterhub",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "jupyterhub-pocketid-client-secret",
        "namespace": "jupyterhub",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "CLIENT_SECRET": "AgCR0kWWHKtCTbHJ7HMM/buf+5vrJtMZW21tMYrDrzjG8epCRjhcjsounF3JWSr02pK1oKoSk+Xal0omtAYBLInP/cXxlyWprBagX4g++Z0JVKroLCmYAYEp3/GxT2O3SIAMB9hZ4T3qANrHlLLT0k+zZ/fKsijuKcYmIGxwrtJc7rn2EIZVEhvVxR09eu6V0xjM+DFX9iVE1QF1KHTtuU0KoqFVHk7qN9YSU6poqRdpSgut5bcg/Z26Wy37K3eid1P7UTOo1XJvyO6P46Ujx/aIPm4nBBZRj6CZPRr4iV3+wXHomhLn53/OZR+kt1zwSCPAaFrdhXirwX8vgIygWF+L4iho6+nTgR/FhpkUMl+FhmIRQE8tZPpbyiFA0jRcz5CXhM1tfE1mWZBtBQ557mBLlzg7dEha/if+DiS3K/gmmGVNdN4Yo1LmWrepiTRpFfaYokLjb8gAelVAzrHIulFHpmm1JiTHkbfFQrqKndOBlyzSyqcfCX1eRJK0vNIHICcKMpkxnF0GbOjv39GPWuxG4ZvmKLtgA6xDN0qpFcUxB4qe5Y16K5HV558Xfj2DiJ1ExqP4KqANKZOUa6oZnHr3CXRrZUpzaAt6XSsQQupIL3UmVOfK5ETdJJEj7V0gzIcuitW0Z/DyIcVcUTiDKK6hEKqHPqbxLTPJJG/IYhsExKDrBx9QeKJca0khA/7KEt/FCrx0f0taxbYSH2eYAoOEqaO594zwmq68QhXUZfQlZg=="
    }
  }
}
