{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "bot-joplin-pswd",
    "namespace": "joplin",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "bot-joplin-pswd",
        "namespace": "joplin",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "password": "AgBd1ZEcZJtLgl71kaDs9Kh6z/13nUmrPb32QAv3lSELZKp9BO+fZ/ex686NDyJMyYZVgn0sCao7iK3jTySfapHn2F7KcAiF4ayjUd7Voe/bKnrsnu7FQjPiyiHHbHlcooFvBklTwLSBM91WcXCeyxJl3v5T12gWH7WxFx9yo2UTGi9TJ41r39gk5doBDbTNnqRrFPEVWPboKyswU6eBf9eC4SfSVhAVBHDfQXwTWUuTlNNopNjFl/AsKoF8t6YUeKMBywmzg6tGOz0kLruf/QvwPmWytzL1YaHkxwnd/EL8fLQAEpSkoqIPIhn1yiF8QGjuDsLo2b8kMRKe/s8iZGUTFaPKC5kppm5s3SaibNWVP4J61Uh5UmFDcL1ZPrJzoGjp7ZpI3NCNVIlFPBytmQUyiY3ldkug35m0mILZhdGojUK4mOY+Zm/iu0JRlakpJn3hfK5GhotA3U7fQODpJ9oeFjN+9HmCk+NZF+32qN9Hfx3PjrVAPM9aF3cY8eGf/wDSUBzgbAZiqwQh1DxZVC53vQFQeNxXtB8vdRy8wB5Br7gUzznl7RJ4H7G+L+t7dJCDOHh+VWKgAhgFq5izTifnKDDp68LTG+btZT5gRs8CcxGY8Qm3sxogulcmtV+5Kprh1LU+tuDi1Wiibw98cY/NXrs6OZUjoE6eqE2OE9HC4VWM9fnWvNoMHrLe5PaCE60ZRU2sGBl4o2ZGvG91LNb77L9er+5YyWTSTxdWjozK"
    }
  }
}
