apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 50m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '65.8.1'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    grafana:
      enabled: true
      adminPassword: admin
      grafana.ini:
        users:
          auto_assign_org_role: Admin
          default_theme: light
        server:
          root_url: https://grafana.${DOMAIN_NAME}
        auth.basic:
          enabled: false
      persistence:
        enabled: false
      # additionalDataSources: # Enable later? But then need dependsOn
      #   - name: Loki
      #     type: loki
      #     url: http://loki-stack:3100 # it listens to 3100 (see k describe)
      #     access: direct
      #     basicAuth: false
      #     isDefault: false
      ingress:
        enabled: true 
        ingressClassName: nginx
        annotations:
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - grafana.${DOMAIN_NAME}
        tls:
          - hosts:
              - grafana.${DOMAIN_NAME}
            secretName: letsencrypt-wildcard-cert-pengiuns.com-production
    prometheus:
      enabled: true