kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-jellyfin-config
  namespace: media
  annotations:
    k8up.io/backup: "true"
spec:
  storageClassName: synology-storage-apps
  # volumeName: pvc-6167bc2c-5b06-4513-bb79-3d3c0e25de15
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
