gateways:
  duckdb:
    connection:
      type: duckdb
      database: db.db

  postgres:
    connection:
      type: postgres
      host: postgresql.pengiuns.com
      port: 5432
      user: jerry
      password: myuserpassword
      database: prod
      # Optional tuning:
      # pre_ping: true
      # concurrent_tasks: 1
      # pretty_sql: true

default_gateway: postgres

model_defaults:
  dialect: postgres
  start: 2025-05-30
