apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.13.2"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      interval: 12h
  values: 
    # experiment to filter paths on immich-proxy immich
    # controller:
    #   allowSnippetAnnotations: "true"
    #   config:
    #     annotations-risk-level: Critical
    controller:
      config:
        enable-access-log: "true"
        log-format-upstream: >
          {"time": "$time_iso8601",
           "remote_addr": "$proxy_protocol_addr",
           "x-forwarded-for": "$proxy_add_x_forwarded_for",
           "method": "$request_method",
           "uri": "$request_uri",
           "status": "$status",
           "bytes_sent": "$body_bytes_sent",
           "referrer": "$http_referer",
           "user_agent": "$http_user_agent",
           "request_time": "$request_time",
           "upstream_response_time": "$upstream_response_time"}

    resources:  # no limit on purpose
      requests:
        memory: "256Mi"  
        cpu: "10m"       
  
  # defaults, no need to adjust
  #   controller:
  #     service:
  #       type: LoadBalancer
  #       ports:
  #         http: 80
  #         https: 443