apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.13.2"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      interval: 12h
  values: 
    controller:
      allowSnippetAnnotations: "true" # experiment to filter paths on immich-proxy immich
      # config:
        # enable-server-snippet: "true" # experiment to filter paths on immich-proxy immich

    resources:  # no limit on purpose
      requests:
        memory: "256Mi"  
        cpu: "10m"       
  
  # defaults, no need to adjust
  #   controller:
  #     service:
  #       type: LoadBalancer
  #       ports:
  #         http: 80
  #         https: 443