apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: fluent-bit:/ServiceAccount:fluent-bit/fluent-bit
  labels:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 4.1.0
    helm.sh/chart: fluent-bit-0.54.0
  name: fluent-bit
  namespace: fluent-bit
