# k apply -f cleanup-pod.yaml
# k exec -it cleanup-pod -n default -- sh
apiVersion: v1
kind: Pod
metadata:
  name: cleanup-pod
  namespace: ollama
spec:
  containers:
  - name: cleanup-container
    image: busybox:latest
    command: ["sh", "-c", "rm -rf /mnt/storage/* && sleep 3600"]
    #command: ["sleep", "infinity"]
    volumeMounts:
    - mountPath: /mnt/storage
      name: volume-to-clean
  volumes:
  - name: volume-to-clean
    persistentVolumeClaim:
      claimName: ollama
  restartPolicy: Never
