# k apply -f debug-pod-pv.yaml
# k exec -it n jellyfin -- sh

apiVersion: v1
kind: Pod
metadata:
  name: jellyfin-debug
  namespace: jellyfin
spec:
  containers:
    - name: jellyfin
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: media-volume
          mountPath: /mnt/media
  volumes:
    - name: media-volume
      persistentVolumeClaim:
        claimName: pvc-radarr-data

