# k apply -f debug-dns.yaml
# k exec -it alpine-dns -- sh
# k delete -f debug-dns.yaml

apiVersion: v1
kind: Pod
metadata:
  name: alpine-dns
  # namespace: default
spec:
  containers:
  - image: alpine
    command:
      - /bin/sh
    args:
      - -c
      - |
        apk update && apk add --update bind-tools && sleep 3600
    imagePullPolicy: IfNotPresent
    name: alpine-dns
  restartPolicy: Always
  dnsPolicy: ClusterFirst