# k apply -f debug-dns.yaml
# k exec -it alpine-dns -- sh
# k delete -f debug-dns.yaml

apiVersion: v1
kind: Pod
metadata:
  name: alpine-dns
  # namespace: default
spec:
  containers:
  - image: alpine
    command:
      - /bin/sh
    args:
      - -c
      - |
        apk update && apk add --update bind-tools && apk add busybox-extras && apk add --no-cache vim && sleep 3600
    imagePullPolicy: IfNotPresent
    name: alpine-dns
  restartPolicy: Always
  dnsPolicy: ClusterFirstWithHostNet
  dnsConfig:
    nameservers:
      - 10.96.0.10
    searches:
      - default.svc.cluster.local
      - svc.cluster.local
      - cluster.local
      - flux-system.svc.cluster.local