# k apply -f debug-dns.yaml
# k exec -it alpine-dns -- sh
# k delete -f debug-dns.yaml

apiVersion: v1
kind: Pod
metadata:
  name: busybox
  # namespace: default
spec:
  containers:
  - image: alpine
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: alpine-dns
  restartPolicy: Always
  dnsPolicy: ClusterFirst