# k apply -f debug-radarr.yaml
# k exec -it -n radarr radarr-debug -- sh
# k delete -f debug-radarr.yaml

# Immich mounts root@immich-server-746b4995c-tzmdk:/usr/src/app/upload#
# So this pod exposes the upload in /data

apiVersion: v1
kind: Pod
metadata:
  name: immich-debug
  namespace: immich
spec:
  nodeSelector:
    kubernetes.io/hostname: kevin 
  containers:
    - name: debug-pod
      # image: busybox
      # command: ["sleep", "3600"]
      image: alpine
      command: ["/bin/sh", "-c", "apk add --no-cache vim && sleep 3600"]
      volumeMounts:
        - mountPath: /data
          name: storage
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: pvc-immich

