apiVersion: v1
kind: Namespace
metadata:
  name: web
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-hostpath-pvc
  namespace: web
spec:
  storageClassName: local-hostpath-kevin
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
