apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
secrets:
  - name: homepage

---

apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    kubernetes.io/service-account.name: homepage

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Home of pengiuns
    theme: dark
    layout:
      Media:
        style: row
        columns: 4
    headerStyle: clean
    language: en
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
      provider: google
    statusStyle: "dot"
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - icon: github.png
              href: https://github.com/JanBenisek/gru-ops
    - Docs:
        - Notion:
            - icon: notion.png
              href: https://www.notion.so/Homelab-074c94b564de4cb7b57de7a7f60e0e1b
  services.yaml: |
    - Vercajk:
        - Grafana:
            icon: grafana.png
            href: https://grafana.pengiuns.com
            description: Them logs!
            namespace: monitoring 
            app: grafana
        - Metabase:
            icon: metabase.png
            href: https://metabase.pengiuns.com
            description: Moar data.
            namespace: metabase 
            app: metabase
        - Proxmox:
            icon: proxmox.png
            href: https://192.168.178.40:8006
            description: VMs for everyone.

    - Tools:
        - IT-Tools:
            icon: it-tools.png
            href: https://it-tools.pengiuns.com/
            description: The Swiss knife of internet
            namespace: it-tools 
            app: it-tools
        - Stirling PDF:
            icon: stirling-pdf.png
            href: https://stirling.pengiuns.com/?lang=en_GB
            description: PDF tools
            namespace: stirling
            app: stirling
        - JupyterHub:
            icon: jupyter.png
            href: https://jupyter.pengiuns.com
            description: Make some cool shit!
            namespace: jupyter
            app: jupyterhub

    - Fun:
        - Hiker:
            icon: go.png
            href: https://hiker.pengiuns.com
            description: Let's go hiking!
            namespace: hiker
            app: hiker
        - LLMs:
            icon: open-webui.png
            href: https://chat.pengiuns.com
            description: Ollama & WebUI locally
            namespace: open-webui
            app: open-webui
        - Funnaiest:
            icon: deepseek.png
            href: https://funnaiest.com
            description: I am so funny
            namespace: funnaiest
            app: funnaiest

    - Media:
        - Jellyfin:
            icon: jellyfin.png
            href: https://jellyfin.pengiuns.com
            description: There be procrastination 
            namespace: media
            app: jellyfin
        - Radarr:
            icon: radarr.png
            href: https://radarr.pengiuns.com
            description: Movies
            namespace: media
            app: radarr
        - Prowlarr:
            icon: prowlarr.png
            href: https://prowlarr.pengiuns.com
            description: Indexer
            namespace: media
            app: radarr
        - qbittorrent:
            icon: qbittorrent.png
            href: https://qbittorrent.pengiuns.com
            description: Torrent
            namespace: media
            app: qbittorrent
        - Sonarr:
            icon: sonarr.png
            href: https://sonarr.pengiuns.com
            description: Shows
            namespace: media
            app: sonarr
        - Bazarr:
            icon: bazarr.png
            href: https://bazarr.pengiuns.com
            description: Subtitles
            namespace: media
            app: bazarr
    
    - Experiments:
      - Router:
          icon: fritzbox.png
          href: https://fritz.box/
          description: Router boi
          widget:
            type: fritzbox
            url: http://192.168.178.1
            fields: ["down", "up", "received", "sent"]
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "Gru"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - search:
        provider: google
        target: _blank
    - openmeteo:
        label: Adliswil
        latitude: 47.31
        longitude: 8.5246
        timezone: "Europe/Berlin"
        units: metric
        cache: 5
  docker.yaml: ""

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
rules: # adjusted: https://github.com/gethomepage/homepage/discussions/2220
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - list
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
  - apiGroups:
      - traefik.containo.us
      - traefik.io # added
    resources:
      - ingressroutes
    verbs:
      - get
      - list
  - apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
      - pods
    verbs:
      - get
      - list
  - apiGroups: # added
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions/status
    verbs:
      - get
  - apiGroups: # new
      - gateway.networking.k8s.io
    resources:
      - httproutes
      - gateways
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homepage
subjects:
  - kind: ServiceAccount
    name: homepage
    namespace: homepage

---

apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
  # annotations:
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80 # Exposes the service on port 80
      protocol: TCP
      targetPort: 3000 # Routes traffic to port 3000 in the app
  # ports:
  #   - port: 3000
  #     targetPort: http
  #     protocol: TCP
  #     name: http
  selector:
    app.kubernetes.io/name: homepage

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: homepage
          image: "ghcr.io/gethomepage/homepage:latest"
          imagePullPolicy: Always
          env:  
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: homepage.${DOMAIN_NAME}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources: # added by me
            requests:
              memory: "256Mi"  
              cpu: "10m"      
            limits:
              memory: "512Mi"  
              cpu: "300m"      
          volumeMounts:
            - mountPath: /app/config/custom.js
              name: homepage-config
              subPath: custom.js
            - mountPath: /app/config/custom.css
              name: homepage-config
              subPath: custom.css
            - mountPath: /app/config/bookmarks.yaml
              name: homepage-config
              subPath: bookmarks.yaml
            - mountPath: /app/config/docker.yaml
              name: homepage-config
              subPath: docker.yaml
            - mountPath: /app/config/kubernetes.yaml
              name: homepage-config
              subPath: kubernetes.yaml
            - mountPath: /app/config/services.yaml
              name: homepage-config
              subPath: services.yaml
            - mountPath: /app/config/settings.yaml
              name: homepage-config
              subPath: settings.yaml
            - mountPath: /app/config/widgets.yaml
              name: homepage-config
              subPath: widgets.yaml
            - mountPath: /app/config/logs
              name: logs
      volumes:
        - name: homepage-config
          configMap:
            name: homepage
        - name: logs
          emptyDir: {}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
    - host: homepage.${DOMAIN_NAME}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: homepage
                port:
                  number: 80 # changed from 3000
  tls:
    - hosts:
        - homepage.${DOMAIN_NAME}
      secretName: letsencrypt-wildcard-cert-pengiuns.com-production