# Is there a better way to manage argo? Maybe by argo?
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30" # after external-dns
spec:
  project: gru
  source:
    repoURL: https://github.com/JanBenisek/gru-ops.git
    targetRevision: main
    path: argocd/manifests/prod/infra/argocd
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: reflector
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
