apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5" # must deploy before CNPG
spec:
  project: gru
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: v1.20.0
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/argocd/manifests/prod/infra/cert-manager/values.yaml
    - repoURL: https://github.com/JanBenisek/gru-ops.git
      targetRevision: main
      path: argocd/manifests/prod/infra/cert-manager
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
