apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30" # deps on external-dns
spec:
  project: gru
  sources:
    # OCI chart source (cert-manager Helm chart)
    - repoURL: oci://quay.io/jetstack
      chart: cert-manager
      targetRevision: v1.19.2
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/argocd/manifests/prod/infra/cert-manager/values.yaml
    # - path: .
    #   repoURL: oci://quay.io/jetstack/cert-manager
    #   targetRevision: v1.19.2
    #   helm:
    #     releaseName: cert-manager
    #     valueFiles:
    #       - $values/argocd/manifests/prod/infra/cert-manager/values.yaml
    - repoURL: https://github.com/JanBenisek/gru-ops.git
      targetRevision: main
      path: argocd/manifests/prod/infra/cert-manager
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
