apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20" # deps on traefik, sealed-secrets, reflector
spec:
  project: gru
  sources:
    - chart: external-dns
      repoURL: https://kubernetes-sigs.github.io/external-dns/
      targetRevision: 1.19.0
      helm:
        releaseName: external-dns
        valueFiles:
          - $values/argocd/manifests/prod/infra/external-dns/values.yaml
    - repoURL: https://github.com/JanBenisek/gru-ops.git
      targetRevision: main
      path: argocd/manifests/prod/infra/external-dns
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
