apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: gru
  sources:
    - chart: metallb
      repoURL: https://metallb.github.io/metallb
      targetRevision: 0.15.3  
      helm:
        releaseName: metallb
        valueFiles:
          - $values/argocd/manifests/prod/infra/metallb/values.yaml
    - repoURL: https://github.com/JanBenisek/gru-ops.git
      targetRevision: main
      path: argocd/manifests/prod/infra/metallb
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metallb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged