# 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: metrics-server
  annotations:
    argocd.argoproj.io/sync-wave: "10" # no deps
spec:
  project: gru
  source:
    repoURL: https://github.com/JanBenisek/gru-ops.git
    targetRevision: main
    path: argocd/manifests/prod/infra/metrics-server
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metrics-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true