apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: gru
  sources:
    - chart: traefik
      repoURL: https://helm.traefik.io/traefik
      targetRevision: 39.0.6
      helm:
        releaseName: traefik
        valueFiles:
          - $values/argocd/manifests/prod/infra/traefik/values.yaml
    - repoURL: https://github.com/JanBenisek/gru-ops.git
      targetRevision: main
      path: argocd/manifests/prod/infra/traefik
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
