{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "psql-secrets",
    "namespace": "postgresql",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "psql-secrets",
        "namespace": "postgresql",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "user_bot_jerry": "AgCO/zcPVW9Dcmhq83miIULRdkVjy4lOYmbCRAzvk+nEeF7prdh14dDAousSvdazzCsgRvyelX9MDgXmPQFHop71h32+lGyeyfm05ulWHZvTRyPIxA2cS3wcEYNBTKYDC9piS7B+IW7wEYmERbA8AUJr2uRCiT+5baXPiJYl0e+PAnVygs/ByF10vWNBl54AD+ddRKTUxRkGsjlQZLo9pF4/QwUVdn+ZwRRnYE71yhFDhtye1lWQ/53ViuqlfVV1gijiX8sHR1mZfPE0VwuaB/AwxECNj8biCLLgamjKw7ez4REO+o+l5/ZwC5IzR7gcwE2mGXhnk0nwOD/TDIUu3jUYtesaY9aoFnjVHJDJSfWmLcKTyo2jVouI3sc2HHDLiyrOo8y/QjcwGrNtt2HTj8FvNaamSy7Bg9B1kHhn4v9uRxPl4AwvxXK89V7iZfYj661qfkFbwDYxP8EBJsEzpMhIPoDnYQnS4U7Zj+tVWjgiXA3qDhK6w5Ts6akEMpEjb8p9lcO93/cjpgCM/8pqaJf6bFgsYD+SAL7I3PQGDA6oCnpOa94uodeJ+H9GLsRkVnz7KHo4RCY3FaduYC72jTLltOqVXyAX3Zw/RIVLOxpH+7Cdp0JwPVuINgAP60dDvkC4m/k8AxAqNMQrYkr4Ow9ybkPASkk5t7ofbGIyfqN12N//Vxc72Z9/3eA7EWQdmU79b64rnNHWZzK0ioezLvPrBy2LSCg=",
      "user_postgres": "AgA1Q7NRuR8Ma/iUTGSKBAecQHGAm6yC5AjmcQUUgC/8fNbWejgH6mcXuN5zV6Hy06z4e0sz3Tn2nfkI4iTjU9cKI+uBDx6s5DCMPwAkq405jTzrumPGzcO6C97PLXW78wr/34jcE9JidJJxO92mpivoj8cVutIa1Q98qFI8UJ7M1Isy8R9wbnyIFOSJjPx7wjKmWNbcLsrSxoFKv+9XNFDqWPHMRd5Fl44zlhNXEF7RlxccVXC8gBKp676k9ioZK7otk94cS+PMOSbf2py/SBdxEvm+C+jP0PVtAcrjH312GWYETyI9LNUzBpK8iHqpxfMvBjIZXBCd/wiDESgDRq00RYTzYAHbqXLSdpulroz/b6wiiqEAXpvCl/laa/o0A8NiRs/uU5HqmAciKUMoWGCKtYaQ0XmGO0PpRiN03taNtWBmBWTfQCstivr9fDLubh6uvmY3DAyQL4ciLUFh5O6g90iggDjsY+VpH0BF5t64ZWnfVeZ6jiHvdVOtNxH/3DdaqqqWAf3MiQ2faZWzFm0ZmMArWNXT2cNaCqtyEj1Yv8bLNAbvA2QNZtCh1+ACpNEKB7imWxV4OGLIQSMMyXA23GGJklHxQ2tDp9SfGL1C0JWw49z/slMfwPg9euNayjMujkzh/NkUKE2rTQVBgZ2G/5uaAzjP1vwZ+jILr8gEagjAm5BpqhjpoY5UI1j1IAqF0AMakoUvUlkF8WFTN+b/g3Q="
    }
  }
}
