config:
  clients:
    - url: http://loki:3100/loki/api/v1/push

daemonset:
  enabled: true

resources:
  limits:
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Scrape configs
configmap:
  enabled: true
