kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-trillium
  namespace: trillium
spec:
  storageClassName: local-hostpath-kevin
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
