apiVersion: "openebs.io/v1beta2"
kind: DiskPool
metadata:
  name: pool-on-stuart
  namespace: openebs
spec:
  node: stuart
  disks: ["/dev/disk/by-id/wwn-0x500a0751e8ac173c"] # from `t get disks -n "192.168.178.39" sda -o yaml`
  topology:
    labelled:
      topology-key: topology-kevin