apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-hostpath-stuart
  namespace: openebs
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: "hostpath"
      - name: BasePath
        value: /var/mnt/storage
provisioner: openebs.io/local
reclaimPolicy: Delete # is default
volumeBindingMode: WaitForFirstConsumer
# https://openebs.io/docs/user-guides/local-storage-user-guide/local-pv-hostpath/hostpath-configuration
allowedTopologies:
- matchLabelExpressions:
  - key: kubernetes.io/hostname
    values:
    - stuart