apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-hostpath-kevin
  namespace: openebs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: "hostpath"
      - name: BasePath
        value: /dev/sda
provisioner: openebs.io/local
volumeBindingMode: WaitForFirstConsumer
# https://openebs.io/docs/user-guides/local-storage-user-guide/local-pv-hostpath/hostpath-configuration
allowedTopologies:
- matchLabelExpressions:
  - key: kubernetes.io/hostname
    values:
    - kevin

# - name: NodeAffinityLabels
#   list:
#     - "kubernetes.io/hostname=kevin"