apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-registry-config
  namespace: docker-registry
data:
  # docs: https://distribution.github.io/distribution/about/configuration/#list-of-configuration-options
  config.yml: |
    version: 0.1
    log:
      level: debug
      fields:
        service: registry
    storage:
      delete:
        enabled: true
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]