kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-docker-registry
  namespace: docker-registry
spec:
  storageClassName: local-hostpath-kevin
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
