kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-radarr-media
  namespace: radarr
spec:
  storageClassName: local-hostpath-stuart-media
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
