{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "hetzner-credentials",
    "namespace": "k8up",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "hetzner-credentials",
        "namespace": "k8up",
        "creationTimestamp": null,
        "annotations": {
          "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
          "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true",
          "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "immich,cnpg"
        }
      }
    },
    "encryptedData": {
      "password": "AgBdFUuH/Sc4+q7SirBjbQff0rHXq7ulZP9jvZ1mpYrB4qKkMYrc9XGRqe1s6qDLcUMr4Bz7aM1d4cAgofQo27wWCkFs/KjBmJUhyPXaVlCq9xMWzFG5nwkeAv99QZhyXARCfXuTpSdnfdPEnqx977ORd95HepjtlaNU1ATR4DgwTLn9x2UmsTYWHnRPaE+gh82A/i9xF1cEcrvmAPZIZdpVPP66cqID2F/4Iy7vnNRwOeJevn+Mty+vE3wZEDftd7pcUcO/fBwDuF2WOMRqzVqPTIVemVSAiUkRqJwkLKaKLjpuvEx5rVzqGG9hUzlR1DhrjhDUIJflgC3Ojd5j9UNLqZ/a8pIAOMFKgyklWCE7NyCr3HhViF2OM24WwXdgwARpbAs3H7wyWfCAadKTT2eCtYIBKp2hNzXZhIFkB5bYLw2oalu5D/UmXGFR9SRDsgBw8GlZDP3seG6+rbvsxig2FW83Es4VO9zf7cybo/D7jFmREZ1LQn2uDWgkFJrmmNlMX0o7dnKPcMli4BAgXH6Y9IbqZSgSdOroOJJ9vaXC3M087ArgpSRmvKLQiJ1TFe8dFdwPy+e9q3yIq9VvuXA73+1Dyh8IrCxnXRXxE5o+DI1xVzOLyXfPMtG5nlFMCPgDJC9dX1ECpi8eFB0IzT4FNAZHDlke5fKPjP8Cm/LXIesMm/HwrCwpjMp5RYS1hO7NIFMGCpPQh9sFm0sXJhvkUj3BAeIjBULG+sVQq8qpOYvTj6qP8fQd",
      "username": "AgB3nXlwK8+pTVlLwyiU+3B7aNk5eaJgbhZQ/ztbY/jbtq+ejhrCadTnDgap5vfnIFZrdg5kQAGOUZmBmZfuZuKmmqQQHjtYwbWY6aVxWghh+t5IHtNaY7ogMpBDVKWDCVXaJxjh5m+z+xwhBQuaoCWirvv2zVkqRavPCRUqhQMkqJ/KqKZkRo0LncOMh5hEElmu5yhEMljTognzzB+UC1ayquBrHL6b2wj1OBIU8eyWGgWuG1H60iIcnfDCIQheSvKVe+Oxr5WWasn2iGLsbMZPa6TqNRoP4uA7GC6YBY+ZssLyrlhDHBa34tD05grJEcI+nG+tmUInvd7quOcNt2r53IZkGEVTaimBGGxp0VTlkYsNI8Xjd/z4MK+5efOioaQGF4W3pcUJ1LjknNqWls/PMseHeLf98nEc1wCbGCU2zixkhlmliSlOEnRR6HFroZMErWRm9xylqrrPxauhqP3ObaK+ibfk4KIYsQwSV+2TcwPzTTMHnXjJ7FR5rCYkEMcPoZqRBzW7lEh+rlYdGFBvISJlCXgUHhSpFSrB/Pa21ScVQIMuGIvmZAhXvvXSe3Lngg9KOTB28CencOqYxVH/wWS2y1BnVwevUmIBBMxga1DWClC7zBg+sj+czrHVBabPHfiALmOLw3EXYPEepZoeQyXruDfUanwDaQt5mSW/NzZY2lbEI6kSd+G2RgaPpDLJ5C5pPCv88GMYp1dh6KSD/Dl4yA=="
    }
  }
}
