{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "hetzner-credentials",
    "namespace": "k8up",
    "creationTimestamp": null,
    # "annotations": {
    #   "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
    #   "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "immich"
    # }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "hetzner-credentials",
        "namespace": "k8up",
        "creationTimestamp": null
        "annotations": {
          "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
          "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "immich"
        }
      }
    },
    "encryptedData": {
      "password": "AgBWZTyCybD/DTgv2lnTRCt8E9Qcx+Gn/JuUmL930m3Y5iQqwmt01FdLtEGEA/Y83f57gfTo2sx5PpY8TB/SrZgX1mEhVBuF7IzOz2S2UaDzQljirrS7Cr34Gi33aI3RrWwNC9G4BDVPoB2sd4A9rdM1FHH9YRofprEHlm7jvwYLnI5eFbBXU+hlcLnf8Sp2XA7jZGDBPVOTwni/XCGreqEr9Bxtoh63ylLPXHwCZep14LJm/P6AvBXUa2zwqeiDd5WuKaxqMRl86bzXarqqoZQ6IuW9q3E4q85ijqwflcuPYbwI9dJsCPZo8QiK3skeObgOs6NP1oxWMg1KCf14X2M0hy1C0f3UFR97lD1wztA2icSp3NRALZwfUg+l2bzsRM5AogmvUc83sKi7OenkFSXV34zmYzv5hekxqyC0zoFFZBQ15LwcxFLLGGOfhap1WyCkb36x7E1de1jSEaC54zZSjPVTYT3mx6lBJeb5NSwpYBU5BonwSqd8PrGp8DcOaZI6FzpYPPjt3lJdA2LaRH99laUsnH08WEGReHfVQNOUMPUhOwKOeIcZk36q95lJJIi+sZ3tDRlPGR/CTieTOMC52vkYpnuWPmVi5ZqD4M9aqyhO+Mw0h3KywvaqdryIkB1riZNpZJQqOY7QECHG3OK1U1DlCpvWyTYnrfOvpA0VGmEP4CrHC4asxHhxQm3ZYfmsnQ0CoJmiInoskL0ZJAw6qI3mhgIytg/mIbodu8nQwMeqa8eyd5sV",
      "username": "AgCcqBxUmV55ksqhIhflsgACsnpo/V6jud0TjVo7rMUz0cq+Xd7Qv2+3b4rNSwDfhhDJHm5yvEAaQhpCBdvda/svGt/2CY8HV2fyh7CU1WehhahZkjiJX6wDvmJVYh9RepduTDJBzXdeiFT+gxLSP/nFZcNxCjGnWC/e5JC72L/NXc1j/GJJZDrz4mErTrtMIUOkno88lktVCA1JTWe7Pxe4C3mdnR+E8MlsqH0UKDFAPLN4/93HzOf2ybOo9BOK1VTYq0TgMkSCIyw+HfU81d6krOL4OpZtXdEJwmnwkV3x3TwELpa/mmd3JuHoLGIvBiTevgx7A3WUW3boHlmISC0RiaOlnbH/yUQSKQw8DL6AP6aEDbR1bqnO9g0MBA4/YhoCPC8njeHo1XxcIFvJz1iBubBbyWoG/No7ZGOHFNM2twSfewjSLpXyEDQ9ouyG8hG6c1Zi5Fm0awjeWapTcXIYaFH9fPUaoVlACr02wZpJMAn/E97ibFAbWL2qk/sWVYYAjo/M9mxkDVligKhqPcW5UZtsEwK6GrSjnj0OwZ+61vfb4VSvozwDF5i0B0ww99tWRyXaltO42AkosVAg7H6fCYVLtytW030ieceA9Xugm4WWKz/lxV/n0inauOGibg86tJT2kb1jBQePyETk07BEc/uQt8fnRlj1ZirDNzLTwzrrNYdhaM2x3flOJFxpOFp1inKG1l0540fzqDyrQOhUtT9XhA=="
    }
  }
}
