{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "restic-credentials",
    "namespace": "k8up",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "restic-credentials",
        "namespace": "k8up",
        "creationTimestamp": null,
        "annotations": {
          "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
          "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true",
          "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "immich"
        }
      }
    },
    "encryptedData": {
      "password": "AgB8rvDrnbX2SNXgWfMaASoKYycnHFzdVc/avZTGdoyEi2QUVngpi2RG/bs0mb+6by3yYQzdYk1dd+TE1K/vskDZzEGoJ8bj0lGAXXEeZ+QXI/CqwiSnicuh48g9DDENVTDuMYFNL+HF9T4lPTrhjxEEjMo3VZAfGkFv82oanQCkmNmFWlXuYrjkT/iLljbKv0gVTUNkVb6frWGyw45tPbcUotbuCMsLTwGN8KDh6+NEkS62WF32yHC4raH/iFhdPBfYtx2+9vFOMo7CGDOIUUMw8F67olDRe0ReyQ6kyYs740Tw3gzNfZTKLkNyu468Uwp1qP3gWzesUoIsmG73GZifPhEkf/QyDhyKnSEshaEc0e47BmONwg8uLKjHrWYos+5NwAvfCo7D4tZkeZxHZzuKKeKg8vHhTou9+nAjmn5+sT5AWSI3S20ZZaMerUcAY2v7jNaPOAXOid+Y0fvB1XKQRni7ALurgeOSpGFIBY53wluQXwLwVAQYa5qA5tz/tO6zRfd4KfW6EATUUWynMxHlaNBmAQZ+0gRffyJj9ih2Zxe1anLtOP2tFJDVcMNjTVmCx6+jGC/h+EhAlPQhVY87WThwusYB4jca9BJHgHMW9eJE7tMQl+awB60dW/kCZjrOxzoImgpm2K6/9Ieow+AjVk3LO33o4IlwMI/o4tx325eJ/VAojREpSVjQAMEUZSQ7NXA8p4I8//hFsSdrJVRqCDIFHx911A1bEiwHUCaa"
    }
  }
}
