apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-logs
  namespace: onlyoffice
spec:
  storageClassName: synology-storage-ephemeral
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
  namespace: onlyoffice
spec:
  storageClassName: synology-storage-apps
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-lib
  namespace: onlyoffice
spec:
  storageClassName: synology-storage-apps
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-db
  namespace: onlyoffice
spec:
  storageClassName: synology-storage-apps
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
