apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-logs
  namespace: onlyoffice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
  namespace: onlyoffice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-lib
  namespace: onlyoffice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-db
  namespace: onlyoffice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
