{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "filebrowser-oidc-client",
    "namespace": "filebrowser",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "filebrowser-oidc-client",
        "namespace": "filebrowser",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "id": "AgBQ2EdpqL3b4GkKtbNx5Nc9DaOGaSZtZ6CU6iFVGQ+Vh2FfZwgIygfm3YF5UAgCsLDVZOZfyIJtx0CYp7Fk42lC6ACj/xaF9M/C9HilIEm+TMYg1pBWLmOv1kWdZ3jBgSVhTLFPIupS0Gv+GAfE8M6Lvv61QC9UkTGjqFm6bJwu3QQnioEEBbYSeFQqIy/XE0siO89v2ichMjVzznSfrHPvIaAZJxgP2iuaIeOfnLoUlJkc/6i/la0g0oWv9PMaw+b+DAyWcZOdAcPHvSU1iZ2eear1GLLRlg7tuKSK4P9ift7LvzYUJxEnf4nDEaxlzWCOse74qG3wObRcsExc/+QvcY+AVpzcTH5jeqMVwnyN1YQxpdYVBFGR/WPejldO1qMlHC7F3zJGm0THQIlWPiyEqMcL5qH0a0ihnfj4BVIB3qwHwEps6uj44nUK1TuUUGTiEbkK/wltxTicvxxaqK9JM/XXPi2muEYeS8/zDqHFkjQ9pPMulofEEVJ7DNc1vyn6eSOxX2iSjlMPbwP1GcXzzo5qMt1czrQTIHT4ha7sR9+A4miyGZjJ3QD44n81MECQrkozuehLTWi7FlQuuBxHApMAPhYu6VcFt5YvfLAx/9NeB+uNiNsvQcOnU+PO0KkxS/z7pAUPRevpRmXsuV4TcD+tti/wZPywJLUyBGP6hTumzno0JBGnTOURaqvu7uxKps2YaMCPpoyNObfOl94c4qYF/g6K0RNehhEEHhX3meFkDXE=",
      "secret": "AgAixsn4674TM+9+TtBhAYYCCx27hRplIjQtduzagxpTA+H5Ld2IL8UJJk+tc0DBopCCsvkpf2rabIwjjk55807SYRRiAksKd+J5PTFjV6kLrLxQuRAV9uqN6HFHAfFcuxJAhEFeVu/ZRgKPVmDu8+9lVdI4uUzp1QYNpJ8eIe87nc/mh+dVeffrm1O4/DicbHc2EYJo9m9fI/qKMGhSvJN8woaLzKSyfuD9mEZuohLLwkN6VRYr69g84a5/LTF8rhErSahbau2HSMfyiDF3rWzGZZuF3xKiMKUSzcl5Djoa2w3zpI4bN+cx6Pd9w9gi3tJCKf5/o+fnqtHV1ISPUt+l1gWZmJEvgxwweSziQa7zC6cDm98AFXq40DryHFggYlK0b3F1tG5aTP3KCzA19AJJxYRgqTxqwqJsn/Qiq0t+UNIloLmTzv3JCP0nRCKAZuRNVGJR9TXKXbLbNZJShWAv9ygRM4UbrjTHrLdNFWjHzluX47AMvecXjPgCptFU0CYhPXGZqHvZR9FZ4YvHV+DmK/inPjX47Z4tBjjYK8o6EwCfVLc9aCyojoIcaZu506MN/YUbT4sTMlreMisJP/e1FpTJ9b87KcMQ1bdelmlAwPdmu6zxEpKwqEmHiCwdsIP8qRF3+gGdMBJLt41MeMFe3FilIFkKSKPwTUL+VMjK15y5Fupu4D+yzViBqF1jxitgX6SLmWoGSELqHYlBGj8lRF1A9fThbGkSLj74m3JhEw=="
    }
  }
}
