{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "filebrowser-oidc-client",
    "namespace": "filebrowser",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "filebrowser-oidc-client",
        "namespace": "filebrowser",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "id": "AgBJXc1HuAmr6BV7Ag8CsLteJdOoAZaJ5ZaL/zBAS/8IU/qb+mI0Zz7B0/+AID4K3ydoYQ69wv5GfPnfUSAmXVuJeKBEOOQFZRdlUPpvm+scKBTYiqVag0OTKVobuB8ZM0hPeujL8G573iJX5wR3AcYv67TSxXqyUgPdKLS74JRreiLjOVexPzX/SIJJ5xiVyUqC+8+Qovf2XsTaAscMYbpbNTMs7U0t3Hsy/R83e2Dn3lpTEKAYHK4/HxJi3YVNzQo0qlKBTRTh/qQeifpSfyydflI05cNdvzMtNowq/M/UN3g94CrGuF03xxj1FSvm1X8QoLuP/M4HiqzACydeWykqEGT+9J7QF9jsGieLU9S8kcaPoBnB79OZlxVrXqVoJ+rk+9Ms6AHDYhM0mMPJmeUSqFfhBiwEwts/B4srLWoKoEASc+kqy0uuyrSHeTuwJ/QoA92U2XX+wivbIpJovzHeYMx7u8XUASKoQrLHYrFbVHmtMtFp65r9F+BvdKqcvpXxMbdrQ0pmaQwUiHb3Ou3l090nuRH647KZf078LzhpbEOcMKUL8ZwmnoNYFmtcHQeywuXiMbez3CpVQoShY8O1kezE/JqGd355vYkRBwJ6VGet4bNsqrYG9Ma5GFkqP5DqSsX88rw4NcDSkoCk6THXSclCDEqFRAsDAPxS5YR+a484WdNrhbaGfB/05Kw3Hs6vBEy+keqx+nEBsjjwau7ilLvjxSnRJmox3XhDrVvPss4KfXo=",
      "secret": "AgCE+cqlQnXf4aPn1aa5bTPvRu5Kda0NGsg9VrqN16sZCq2Qq93efUi0veBynX0IEShUBHoiK+cn76sbFnGDH4LkFJ/T0hIQh91ife+c2wjEYI+KAkJG15xWlwyjhxUKH7QVqh7s4ExRSzcfHsuDCjnkg2hpboBu+9cVCbsgvFF9Ya2Llfgo2zjEigbnuA/UEpI3XXo+DWCJIDWPcLTQMAN2ISulSQuocwuwwXYd8dXH9euyesEHUnxnhAnCIfBidUzoSfT6l3uVY+UrI+w3kbJsQmBqSEkd8lbvsbMIeTMvXWoY3Re9mxE38tX8KRoxp6hxc1Km2DUeb9No5NQf2OsW8KpooPKeIlFxLgtt8G95IRATCP7hvM98XOHk/0yLortyPvhL892j6IywhEINzq9d8RI7w6DLq/7QFitSBZtQlsm/5d2Jn1Uf7pZdYuOtwi01+NIGmLRK2lY82p6Y9hXtsilSYyokvvMOYerCpubO30rhKJP8ZDNcFCWKBSobJz6yj1oxnh+7kwSax9spBf/PxBH1AKFxCXcg6ma1WtnSjAFO02PIUFW4tXdDjHor5/Yts8CuO3gzC+asjY4YN4adc/XinafFFpvXgNddYqVYkmsoz6zlmWnzLc1IFHVtQS9XlyyjbjZu6Tpe8eOTwPZWZN23n/56VLaA7JzcPs5CZNkZV/BCYX+ssBaepli1MMMcQ9G9UKKV/QB9sCi6SZYbd7YSCxZcURBPQImq4gYrIln54V4="
    }
  }
}
