{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "filebrowser-oidc-client",
    "namespace": "filebrowser",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "filebrowser-oidc-client",
        "namespace": "filebrowser",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "id": "AgCO5WY81rBRQPnGdE3lMxz9rpfqswtEgy3wDehCodjpwsZoPuKQcOfrKLtrG7AE07gW7m0f1MnD8p+Brp3G9tP5yjiG0rO3zUGhdjAUs3RErvIzeo1sW8h3j9MjjT41JEj3Z3dsgWndYeqvjJyxy+7wAaJWKlUB7WwCnyyIcwC6OrDetjnZAiyTZohpRRiUzeOgVQFu4iGbSt1PsIiREglxO8iQN0c3VTRAOwWz91N4JFkSffJR0Z/kRqaaWUv7qIqO0pFBQY9q8+JSM2e/mzOxrBbXG0vT/K8qEdwlTa5FLm1IcH0pDQLXq3xG43AXHpjDL3INGLOIwCwzVKYOEbJYI3uBK1TW9zERU6rzNXb/ShCbRu2nLicSNYxFxsDIYWhRzs4Sa63TS3sUM3n4idDBI9O99pPr9pyUE0JUgTWhVeC6i/HLHrvNQypjuMYc6YrvixY2O5adttDbQxevemUMvYdhKXVgs0dX3Y8rRM8xdUiistPIk5iSvheI0/tKIDRTMX9ItJjJYy0pPmL20fTv7e/aK7M17mqCEUKv2e/aDrHJtCnDgo6IiNYSr3RRUC4tz5pfoigVZ9bv5t0eOJOXdwSz+Q+29ncPLyfDygHVDKWptyQr8Wq1XXe4Lmr75rDpnfOVc0D4GmCorHvHXhAv4d/nAkHDr+/YszUM4umuokt5MjKCKF/dequtiSarvGWZEPgl90tYS18yDSVQjDE9n1cM0YzPzP7ajrcjbf0HDIZxM+4=",
      "secret": "AgAnVsVIGbrst+uzEdm1G4wBueE2D3icqY6yojwfFC2gSU8ldTqgLZ/rqRbIliJ8Xn9MnL7Kv1++eW4FnW94F/bkYVK/NtAmSi3m0n7iQU7tLo7MN6QSr/2QEn3lG4w5+Q62GCbGo7eCHNK/4Z87EFhkedvdfGorChiZ1u8r3y8CJyxsPQkWREKMp4ibIQ0rxNbMXT7s6CIvt4/AVej7+lrh7+sSPyrKXhWHu3u+M/yjbU3nUD0UkQVDww5MVP55f9uJvtIlHBlOfBdEBhrV9FkIIenHvcPIt+sA5m/8MzO1X0/5NsZS6CmqC7r/+cpxzOScu5GeZ6q9wqrWvCeGfsVuU0VlbCEFCkZRuIC1kntDI3OOrBbJBjSoUJZkXkKajE1vIoTj/zgsBS/oRFCMGmgEuQWQGQy/UlmDqEYBBmTOmpJXxe6ltmz7YpjAQ9hX6aVgw+SIMU3UC2ESF0FduToVjRpywDgcsByWQXN17BbbgjfgV4AXPABDp1Zl/GXxTe0qxc/wBeDK1b1TAIgmvaYXvny9ZLUuI0c7HeJfLjv1mNkb5xj7bfGncjTWIOv7eVuQP+A5nZq0q4YG8BdBo29siqTfkDcj5eIJxPuiVOUuwqXu5FDaq7R67U4132H2mbFyffLyrl4z5v3NmN8/NiWm/wrRsJBVjekCYe3616eyATqAqy8YUlwurVTmhmR59XD3CdT4FZBqtEmqsvxBUdYYNFKgNERfFWt2Dm2is15lYw=="
    }
  }
}
