apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - metallb.yaml
  - metallb-crds.yaml
  - ingress-nginx.yaml
  - sealed-secrets.yaml
  - external-dns.yaml
  - cert-manager.yaml
  - certs.yaml
  - secret-replicator.yaml
  # - hiker.yaml
  # - stirling.yaml
  # - grafana.yaml
  # - loki.yaml
  # - it-tools.yaml
  # - homepage.yaml
configMapGenerator:
  - name: gru-values
    envs:
      - .env
configurations:
  - kustomizeconfig.yaml