apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - metallb.yaml
  - metallb-crds.yaml
  - podinfo.yaml
  - external-dns.yaml
  - cert-manager.yaml
  - certs.yaml
  - secret-replicator.yaml
  # - ingress-nginx.yaml
  - ingress-traefik.yaml