apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - metallb.yaml
  - metallb-crds.yaml
  - ingress-nginx.yaml
  - sealed-secrets.yaml
  - external-dns-secrets.yaml
  - external-dns.yaml
  - cert-manager-secrets.yaml # might not be the best, let's review
  - cert-manager.yaml
  - certs.yaml #it takes a ~10m to set up and propagate, patience!
  - secret-replicator.yaml
  - openebs.yaml
  - docker-registry.yaml
  - cloudflare-secrets.yaml
  - cloudflare.yaml
  # Apps
  - hiker.yaml
  - stirling.yaml
  - grafana.yaml
  - loki.yaml
  - it-tools.yaml
  - homepage.yaml
  - ollama.yaml
  - open-webui.yaml
  - jupyter.yaml
  - media-init.yaml
  - media-jellyfin.yaml
  - media-prowlarr.yaml
  - media-qbittorrent.yaml
  - media-radarr.yaml
  - media-sonarr.yaml
  - media-bazarr.yaml
  - funnaiest.yaml
  - postgresql.yaml
  - metabase.yaml
  # - collabora.yaml
  - nextcloud.yaml
  # - joplin.yaml
  # - immich-cnpg-crds.yaml
  # - immich-cnpg.yaml
  # - immich-app.yaml
configMapGenerator:
  - name: gru-values
    envs:
      - .env
configurations:
  - kustomizeconfig.yaml
