apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: open-webui
  namespace: flux-system
spec:
  path: ./gitops/manifests/open-webui
  interval: 15m
  prune: true
  timeout: 10m
  validation: server
  dependsOn:
    - name: external-dns
      namespace: flux-system
    - name: openebs
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: gru-values
  # healthChecks: # no deployment
  #   - apiVersion: apps/v1
  #     kind: Deployment
  #     name: ollama
  #     namespace: ollama