apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kuberay
resources:
  - raycluster_helm.yaml
  # - raycluster_kustomize.yaml
  # - ingress.yaml
  # - raycluster-embed-grafana.yaml
  # - rayjob.yaml
