apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kuberay
resources:
  - raycluster_helm.yaml
  # - ingress.yaml #does not work, bastard
  # - raycluster_kustomize.yaml=
  # - raycluster-embed-grafana.yaml
  # - rayjob.yaml
