apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: joplin
  namespace: joplin
spec:
  interval: 30m
  chart:
    spec:
      chart: joplin
      version: "1.2.1"
      sourceRef:
        kind: HelmRepository
        name: joplin
        namespace: joplin
      interval: 12h
  values:
    # here
    define: &containerPort 22300

    postgresql:
      enabled: false

    common:
      name: joplin


      service:
        type: ClusterIP
        enabled: true
        servicePort: *containerPort
        containerPort: *containerPort
        extraLabels: {}

      # deployment
      deployment:
        memoryRequest: 2Gi
        cpuRequest: 500m
        memoryLimit: 2Gi
        cpuLimit: 500m
        port: *containerPort
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxUnavailable: 25%
            maxSurge: 25%

      # container
      image:
        repositorySettings:
          isPrivate: false
          secretName: null
        repository: joplin/server
        tag: 3.0-beta
        pullPolicy: Always

      # ingress
      ingress:
        enabled: true
        hostName: joplin.${DOMAIN_NAME}
        tls:
          enabled: true
          secretName: letsencrypt-wildcard-cert-pengiuns.com-production
        # For Ingress CRD
        ingressClassName: "nginx"
        # For IngressRoute CRD
        isIngressRoute: false
        entrypoint: websecure
        certResolver: letsencrypt # leave empty if you don't use, tls.enabled must be true and secretName must me empty
        annotations:
          kubernetes.io/ingress.class: "nginx"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"

      # env variables
      variables:
        secret:
          POSTGRES_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: bot-joplin-pswd
                key: password
        nonSecret:
          DB_CLIENT: pg
          POSTGRES_DATABASE: "joplin"
          POSTGRES_USER: "bot_joplin"
          POSTGRES_PASSWORD: "joplinpass"
          POSTGRES_HOST: "postgresql.pengiuns.com"
          POSTGRES_PORT: "5432"
          APP_BASE_URL: https://joplin.pengiuns.com
          MAILER_ENABLED: 0 # set to 1 to enable mailing
          MAILER_HOST: "mail.une-tasse-de.cafe"
          MAILER_PORT: 25
          MAILER_SECURITY: "none"
          MAILER_NOREPLY_NAME: "Joplin Server"
          MAILER_NOREPLY_EMAIL: "noreply@une-tasse-de.cafe"

      # horizontal autoscaler
      hpa:
        enabled: false
        minReplicas: 1
        maxReplicas: 2
        avgCpuUtilization: 50

      # startupProbe
      startupProbeEnabled: false
      startupProbe:
        httpGet:
          path: "/"
          port: *containerPort
        periodSeconds: 10
        failureThreshold: 20
        timeoutSeconds: 1

      # readinessProbe
      readinessProbeEnabled: true
      readinessProbe:
        tcpSocket:
          port: *containerPort
        initialDelaySeconds: 30
        periodSeconds: 30
        failureThreshold: 2
        timeoutSeconds: 3

      # livenessProbe
      livenessProbeEnabled: true
      livenessProbe:
        tcpSocket:
          port: *containerPort
        initialDelaySeconds: 30
        periodSeconds: 60
        failureThreshold: 1
        timeoutSeconds: 3

      persistence:
        enabled: false # no need for persistence if you use postgresql

      tests:
        classicHttp: # default helm test method
          enabled: false
        curlHostHeader: # curl using ingress.hostName as Host in header
          enabled: true
          path: "/api/ping"