{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-api-token",
    "namespace": "external-dns",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-api-token",
        "namespace": "external-dns",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "apiKey": "AgBkIBvJgFxoJUXXhR2of3s5lp0TFeh2SmF9rbJQEuqmx83MRZDzAbJwfkWVwp1H+9f+7ydI7+z4JR3hWU3fIqkOucXC3+M0PU2G5TpcY2Zy4iKOOgeV+gNuxukEveJRQrSPqVTLWfGmO/JSgvgoIQiEUaJvH113pold2w0fsm1bF2ukEJNipScAFtgy9yqNHkUNRmG45VssrQbyPDgkZYtUrC+IwUixQBU9/wSafSkBlTp/w+jA5XtMdI00/u5Zr1gyvJdvFF0VUleMgsKnNHI+hOeIWctT7lp6GaBpVCjGS05Zfc85/uG1oDv04zXz7Fz9GAuKO+ZN/4XZLe4n239JnfxLe9Yb5v3iRUOdAy6KbT2J182H4f7DTmK3cLh/0jtgfr9A5DOqAojsymcepBICURGGocSdkMEYswdr3Ei9tj1KCZ1llBg7XRakA929yndb6RyazHGbnsBhCoqfVxgfJ0tZn4gX0Oa/nThSivwfXPDNE2e1hIWlVlEITqMpkJZSzJL/DDiJUQaYUtR6SBO8w+5oy+VY0lR/8fuS/HCA+JOOozoxU9xJ1TLUhImQXoTTP7QDbDD/1CmtqQ2gSdloa6ImK833s5Hstc0p+SWP6lWPT4h+dJhQn7pYN6vNSAM6nKJdyaIIWbxTcfoP7gyC61LIGai/1/KtGqiHUcx2/XOwUbIbD4F69KOKx2dEixJqTFCTtzva0IRWUmM7VNKUlzCDFgDQH17Wwc3Xsxxl1J52ghsaXqr+DWEfgcCaRatWlajLbQ=="
    }
  }
}
