{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-api-token",
    "namespace": "external-dns",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-api-token",
        "namespace": "external-dns",
        "creationTimestamp": null
      },
      "data": null
    },
    "encryptedData": {
      "apiKey": "AgBaKY79MbvYKxxBjEOWNu+0gzq61+l5NSUXBFXLU49IlksQgI3pknQylfUZnvGt1J4nzpVjFhjYCt7X6Na6Ypz/cejgUFo6vTBHjCcUBrrfTSLBbQ1qz9EQcQDFHCeP7tQLH6UlaPzooBYOVSqbY4WXoL/r4uLO2obd7W0fICO6m28TZ5q8lrPPru6wgJ8FVWFQ6BJB4JWSG8CH0OxO5nP9uPSzIasGB8uhfoU/MK8ZoJJWO7+9GAvrpG8OEZHOFUgwkWKaOoBSad4D6tKOn0xWtUtM31Rs0jhKBGq5/gnQM+GWRkNcbJRbnTR/VWn7HkDTyNbHq/FuQoQhPatKhqoYCSE2rY73rGeLf7sdCBEOucTkWAfdgxzqQYUJuWvtKTJ34ReAEWabcseTT3TFZA+xC3lckBtGfmNkktBONoC00NAJq/xavOchRZYI+TrEcnqOrjNhXpJTY8IjepUJuSapkdqIdzpdioUCMZ5oNfpLonjfG4cLJtP/iX6kredBrElMzzEo+29kK2dW1EIBRney9ZlGf0jefet3OE4s8iLOQau6qSyJ8A4P6sJKNKzQ3fXgVEuK3soiExLLLE5g3TN+G7VC7Wkln/qu0ee5RP3PcPWQl40dhBX9vP7YVCNv4Piu5iG2oyEGZC9PW9xTUvnvNlUbv546zDnzvJCiIZM+FdN4COrxltd+bYDOXHlpzAQy6S617MqMfriU0fUfvSHzufd9Pf+GscuXx1niEo1bW4MNcr0brtdPyaHcHz+qSF0Ho8Tyhg=="
    }
  }
}
