apiVersion: apps/v1
kind: Deployment
metadata:
  name: hiker
  namespace: hiker
  labels:
    app: hiker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hiker
  template:
    metadata:
      labels:
        app: hiker
    spec:
      containers:
      - name: nginx
        image: ghcr.io/janbenisek/swisshikefinder:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 # internal port for the app
---
apiVersion: v1
kind: Service
metadata:
  name: hiker
  namespace: hiker
spec:
  selector:
    app: hiker
  ports:
  - name: http
    port: 80 # we talk to 80
    protocol: TCP
    targetPort: 8080 # app listens here
  # type: LoadBalancer # for debugging
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hiker
  annotations:
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "traefik"
spec:
  ingressClassName: traefik
  rules:
  - host: swisshiker.pengiuns.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hiker
            port:
              number: 80
# spec:
#   tls:
#   - hosts:
#       - "dbt.${DOMAIN_NAME}"
#     secretName: dbt-tls
#   rules:
#   - host: "dbt.${DOMAIN_NAME}"
#     http:
#       paths:
#       - pathType: Prefix
#         path: "/"
#         backend:
#           service:
#             name: dbt-docs
#             port:
#               number: 80
