apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv-stuart
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-hostpath-stuart
  hostPath:
    path: /var/mnt/storage/shared-pv-stuart
