kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-cnpg-cluster
  namespace: cnpg
spec:
  storageClassName: local-hostpath-kevin
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
