image:
  repository: metabase/metabase
  tag: "v0.59.2.4"
  pullPolicy: IfNotPresent

monitoring:
  enabled: true

resources:
  requests:
    memory: "2Gi"
    cpu: "200m"
  limits:
    memory: "3Gi"
    cpu: "5000m"

ingress:
  enabled: true
  hosts:
    - "metabase.pengiuns.com"
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/max-body-size: "100M"
    traefik.ingress.kubernetes.io/readtimeout: "1000s"
    traefik.ingress.kubernetes.io/writetimeout: "1000s"
    traefik.ingress.kubernetes.io/idletimeout: "1000s"
    traefik.ingress.kubernetes.io/retries: "3"
  tls:
    - secretName: letsencrypt-wildcard-cert-pengiuns.com-production
      hosts:
        - "metabase.pengiuns.com"

database:
  type: postgres
  host: vchord-postgres.pengiuns.com
  port: 5432
  dbname: metabase
  # username: bot_metabase
  existingSecret: bot-metabase-pswd
  existingSecretUsernameKey: username
  existingSecretPasswordKey: password

service:
  labels:
    app.kubernetes.io/name: "metabase"

podLabels:
  app.kubernetes.io/name: metabase