image:
  repository: metabase/metabase
  tag: "v0.63.1.2"
  pullPolicy: IfNotPresent

monitoring:
  enabled: true

resources:
  requests:
    memory: "2Gi"
    cpu: "200m"
  limits:
    memory: "3Gi"
    cpu: "5000m"

ingress:
  enabled: false  # Disabled - using custom IngressRoute with TinyAuth instead
  labels:
    app.kubernetes.io/name: "metabase"

database:
  type: postgres
  host: vchord-postgres.pengiuns.com
  port: 5432
  dbname: metabase
  # username: bot_metabase
  existingSecret: bot-metabase-pswd
  existingSecretUsernameKey: username
  existingSecretPasswordKey: password

service:
  labels:
    app.kubernetes.io/name: "metabase"

podLabels:
  app.kubernetes.io/name: metabase
