apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: schedule-hetzner
  namespace: k8up
spec:
  backend:
    s3:
      endpoint: https://hel1.your-objectstorage.com
      bucket: pengiunsbackup
      accessKeyIDSecretRef:
        name: minio-credentials
        key: username
      secretAccessKeySecretRef:
        name: minio-credentials
        key: password
    repoPasswordSecretRef:
      name: backup-repo
      key: password
  backup:
    schedule: "0 2 * * *" # runs daily at 2am
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
    # optional
    #promURL: https://prometheus-io-instance:8443
  check:
    schedule: '0 1 * * 1'
    # optional
    #promURL: https://prometheus-io-instance:8443
  prune:
    schedule: '0 1 * * 0'
    retention:
      keepLast: 5
      keepDaily: 14