apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: backup-immich-db-manual
  namespace: cnpg
spec:
  podConfigRef:
    name: backup-env-config-immich-db
  backend:
    s3:
      endpoint: https://fsn1.your-objectstorage.com
      bucket: gru-k8up-backups/postgres/immich/manual/
      accessKeyIDSecretRef:
        name: hetzner-credentials
        key: user
      secretAccessKeySecretRef:
        name: hetzner-credentials
        key: password
    repoPasswordSecretRef:
      name: restic-credentials
      key: password