{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "bot-immich-pswd",
    "namespace": "cnpg",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "bot-immich-pswd",
        "namespace": "cnpg",
        "creationTimestamp": null,
        "annotations": {
          "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
          "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true",
          "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "immich"
        }
      },
      "data": null
    },
    "encryptedData": {
      "password": "AgB6w66NFotT0OHNEwdmRS/CV6zp6of58F8P6Cp6Up8uxWSpgcFfaDxYOgoDPMF7nsvNkm/fG2sh4W9hUhOkoWbQbW8oWJ8Wjnk9rRd+Pzq+dCsFWtTVjdM1R3KUzlKOhiRs4QZwk51e82kgfmQ3XlRMIHaorysm+syy4X9FqK9Z27xMvuVpknWKT97Llyq1SJ2B3F7Vriibv69G7nkikOMYVnPAF/13USGYkHSYgkP/6v+BCu1zNjgVWrPvwDry6BTWC3iEkZIebhPJew6SuruZ9wGjDhAkiQBV28llK9z//lWjkEUElD0xO9yQztxA10MQgXPTQgc6qMT3013E57c3z3UUZNqlJYX1RHru2hIeN6U3AKLWCBouPFI1694Z/CiHNKwQe1zB+rw6q/Y6VESBORYEfmqOPPYBg9299qhX8ZM9OidbJ+PgN6IarhhJnXBytHWECHDgPzJbI9hqYQEtCQBDF7blyXyXUGVFldZQQNR7G3zT1qA39xjRlPSkL1PPU2gStj4nFnUCMTTEtuuc9VJguEhkVLka+J8x4/3ImD6+WBeJEfCyeaiOyGm4oZjX6JX/8Q6nQ0FObBmLTPRoOamiWlJhXCfU5CmvolPJ7VJU9cjoCsgMW67LUfZjOavVFSGp3M+f/avlaml8pvkgK5W/mm60RhuMW1m1uAgCL/FQy5NqyZc9MPLgpo5kEtyNF9fuLU5wlgDVnwOgWFjwiYXASwltb8bH8w2Bkys=",
      "username": "AgAs1C5Z8gCWeJY86uMjuoS2BWn+DvH9HY7uXSWV3TY6E2O6eHj9y8QedHaCE/6viQo3lk2xFxcFAs0ypjsOt75hRMClV7+y0jhuKwqnguyBYriQORwxJ2Nh/Bc5cCS0psNNK7fvqY+KdjeWIw1vAXEb8ON2NkQTRP70TkT6V3yN+9CU/1zEupLAxwtSdHYymr0EFoqb5vbu6p0e1CGPykTZ6avKmAwRE6ztcGGYSQ6N4tnN9J1LM4UYiD3IAU5w7m9JWCOZ6OhDsMjaiFNRcR/iyu3krL+hPsGSWZ2VBGLgY+4qxg9u5fY8kE1lJn0fZTDzPDd1UPvU6NYiYdVD8y+NuzY6HIC6iZeHJFBNiWLLHnUXIG8ZjAtWLFST4zltdzJnU73Q9UC6qLbyPHdLWqhJLYNYUcjeTZcW99uQtDSwf7bE4aEl8DecmRyAQocKqVzYBad2e0f7DjP5Iy1WvVHa4XfmRwIt6pQITroajN9QheyLR/Bu93zYPaG4foD5XQ/CLAweBR6sjtKxFuOTQROssekC3Am3BKskFCRyG/XX04+J5O9+T/2R1dTH4iJrpgaiD9b9MKVq3Fp+6VfRz3TMswT0DVv0aZHI1XWuOxgYfcv4oEPtjVJ4xisgnoftUeDeisSfz/XcszHW7SsXkyUoBsoynfSEtC9M05J1PDhqHtBKAA35hKJyfGLzfqpgizBRd1b/4mIIMM8m"
    }
  }
}
