{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "bot_onlyoffice",
    "namespace": "cnpg",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "bot_onlyoffice",
        "namespace": "cnpg",
        "creationTimestamp": null,
        "annotations": {
          "reflector.v1.k8s.emberstack.com/reflection-allowed": "true",
          "reflector.v1.k8s.emberstack.com/reflection-auto-enabled": "true",
          "reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces": "onlyoffice"
        }
      },
      "data": null
    },
    "encryptedData": {
      "password": "AgCm0TTQdIf/wDwPWJsJveOFJGMK27yjsCKDYPUpek5B46eSUP3NfUONS3M80ra2wFFHzo8DyORwIr7GsAgTWWdN+lhXKcargjbKjCFl0iNdJ+F6L+OjNdfo+i/fCU9HqNRG8hRB2VGB/jbYut+v/+MvcJUdEgRzP/NPG6a6EJXwYySLj29U0WqjTiViPlRXeoAa4Zm3aL0QMEe7lym/yqK/YS/R9Y7LKYjlpjpOC2svdmH8hl6geXzdqD0ynEQkD+KzchRy59FU5zLfglHA7+YaspQEjZXC8vImsUHiOu59UqTCD+pdeBcH1KvCF/HkB8UqLEhF82KrwBHSyrDUYiR9cMhIfMCWukHuBKvlnNUpLZCuBfJFMNzEQGlBiO8sv/AJfPKY0X05evBwO9SK/aUw6Y/bVV4HGD22zMPgmkXQcwRmTnjaQvj7jvFH8KxIpv8z9YLmY2Uh02dn+xWo/U3CQFZforojpo5b0cmMi+xlwlVZWmj5FUi8lWjnPcoNsnvobONUrc9bLb4W1SuSBf5mtG3G9bjQFQv38F4wHYKIwcJWvGvC1aJHzpAq2AB6BGZZW8P1EjE27SlTaTts+fZcindIsGeLUbZ0nBBD9a+2gMpUV/69Bu4m0BE+Ily/M/JtAr9JCnaIH4wiT3n3QIkQ/fBRdPqWBqkGqngSjD2/mW9JX6b5WMwD5YfIEzD3op7xUvi3AuOvr36HONwIbYyPyXMAOJVatMgMmO0="
    }
  }
}
