apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg
  namespace: cnpg
  annotations:
    argocd.argoproj.io/sync-wave: "20"

spec:

  instances: 1
  
  superuserSecret:
    name: superuser-pswd
  
  enableSuperuserAccess: true
    
  resources: 
    requests:
      memory: "2Gi"  
      cpu: "200m"      
    limits:
      memory: "6Gi"  

  imageName: "ghcr.io/tensorchord/cloudnative-vectorchord:18.0-0.5.3" # pg / vchord version
  imagePullPolicy: Always

  postgresql:
    shared_preload_libraries:
      - "vchord"

  storage:
    size: 20Gi
    storageClass: synology-storage-apps

  # Continuous backup to S3 using Barman
  backup:
    barmanObjectStore:
      destinationPath: s3://gru-k8up-backups/barman/postgres/cnpg-cluster/
      endpointURL: https://fsn1.your-objectstorage.com
      s3Credentials:
        accessKeyId:
          name: hetzner-credentials
          key: user
        secretAccessKey:
          name: hetzner-credentials
          key: password
      data:
        compression: gzip
        jobs: 2
      wal:
        compression: gzip
    retentionPolicy: "30d"

  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: cnpg-rw-lb
              annotations:
                external-dns.alpha.kubernetes.io/hostname: vchord-postgres.pengiuns.com
            spec:
              type: LoadBalancer
              loadBalancerIP: 192.168.178.190 # pick from `k get ipaddresspool -A`
              ports:
                - name: postgresql
                  port: 5432
                  targetPort: 5432
                  protocol: TCP
          updateStrategy: patch
