{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-api-token",
    "namespace": "external-dns",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-api-token",
        "namespace": "external-dns",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "cloudflare_api_token": "AgAU2T4vmf/EFkG3CDNcw3yxYlCzgI0HRmqhr+ZLDXdKD01ZEgSgWgXblQbN5f9ceu7HfdicTatrLSpSMRExOYIrYOi5eivVxQOGRFRzyngvHOvKq3jAxUqeOQELCvBTZvPYkPYFE70GUWVCezawBlmS6cO4vkkwBEBvsw/Dn/uuK1TjqT7Qu6mguK0Jm7MrX0ibEe3vC6Tpo1qtP6bCwUMT2Y2ua0OrkdzTjkJkbfC14qnPsaMVYYRt4VXcGLz5HUnw5lf4dMysFr1yhnhkn8bNRiWisUO+x+De342GYRk1Oy4q3v3/wfw9uZZezzWyYFMxPQUj+9W3Noa+1hPWGMs1KsoxsJYoCBUVL9hIWmj9PWuGAVPQz/xg7pqh0IT75D+6bR+gfT19o2VepNFrEwS3YNUcR2Co+5Fcxt4tzKr635a7ZeIqWalZ5TT0SQe1AFXcg0/GDelTEZedSGFovI0v6Z+Sl4PIY2/pxWv+k3lIUNfLPUnyBcgB75/xaeSY7eycRjE3Dn0zF21vTNxtAO3WBpIfnbWSGpxXsMOm2nkmtGsHoVWx/SDWMmarau/8lxvAGe0Lh790qAk1HFCcfC3lwdC250Uivl9LawxfKEPXZ3xOpvVr9vi3BiAvobSZCNesjeFdhJSOp82GP8vwRxXpyK4PfH2NaXoV1e8i4i417YqSyfGfbugAnAr+hsLTQfDF15bwYPld5/sdx/DX8ItDieAjf/jX/R19oANG9AH+CxeNT7xqD3tL"
    }
  }
}
