{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-api-token",
    "namespace": "external-dns",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-api-token",
        "namespace": "external-dns",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "cloudflare_api_token": "AgA8NUK5dMewXVKPpR7aidovwh4+ODEBRgPrjauQtPVNZYLAr0zzR7zHGhQnnu3k6zsLRcyq+lkM8A4uHvp1O8tg8dieyRSnTtJHJnkJYJ1gLAyHt9gRwdx/8nq358xkB4e+3qu24ZU6282s7gGutC4vsS5M3F6kxcH3sU2uTZ0jivUI5bNXpMeld9tVMo+mtgYMLPR14ou1THaW89nwcfnkbC/zCXKrQfEnR+j8/HkqcXAZFyzwwwDkmjZ6c1WSrr6LeEZA4mEEVeZt2L3GmBqWbUTGSThFtbT6AfdIaBPfk711OCzGM/3mGCFOLmogtuF1zl13suXFRSMF/iblrJsPHhANsTS8iQCQpVQiTOVE4T/ZFK5ECwrtcT1uNf8LqNdOJJ/Q4dCkEc1oLGXh4U5a7AXqkkRRJWgoyg1OE1igGbUalaPCnev8aqXAKl50uCtH/D3zc9/q+q7mUM8YFtpsqmb9M/xvwFN/S8KQ09sSsJeyVC5/DcA3WqjS5+sYz9utsMkzbSOyUT9zIHvW+AEDSCFhYvEGg+hSKrCEbsGH83M5IXhb7/XJCE9R8KDVRhREOvuzgjvsTjDSIQTOcHTcQuv4vs79pGyh53m3WwXdXbl8zc41CAIk6wrM8AXEoqecBXuevN+XQwlWCz5EmUWzwEyVPrgncNd+rJnv0eU0wOc2L2nt8EwhNC/yEd2ez7F7UlKCUr4e4FM6biMcdC6YlZd1wIARfiyPwx3R+GZp8XaIA0zipvUO"
    }
  }
}
