{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-api-token",
    "namespace": "external-dns",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-api-token",
        "namespace": "external-dns",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "cloudflare_api_token": "AgBsa2FLNZRZjgxcP/TzEM3kFTssuIS3HPn+XHH8YrsiPKKDqco4WmDSP6KEAiHnsN8szfXROJVKHT3dz4YopDyA6lxWPm1l2DnEyV/PU76p49iVNFeX7USIrBvU6XyEmrMjY9HshctknooPBfK++DSNr93fiF32AjwQWM4kO/pYwgrePTC5O2bU57keYUZeJKebATSrxDXjwhbBwdenr8KocKhqUwI9SWGjOHNsC3O8IXL47XkSgICvjL38h/3ONhp1iRRVT3Rwu0TpeWwk1NADjRmllQvCMSyVbYthDiWfy3Ql7UmNIic4ZtpfJPIQ4QoevHBo5pEQ86nd7gdm6Zo1RzsScYQzhO7SKhnUmSgF9T3gre1eb3lZ73HL0sMC8m4C4PNEWQNxXZUJPbQ2SzjXpSN9w0mQePbRaVqZ02RoOvxhVA+YnqlxFwS/+CBPWpbhUAL70wHvvNpBulHC0Q2HDEEty6whEyKGm7mETeRr0Wr7lZZk7BU/sWewHVA30V6/6AL8Xvehmpp1jSgvyHxEwx/p2sKQohEOC6Mqk9k2rCj7soBkZVoIHSTxo48CRl3wPs+3gRa6zhZRWS1vjUjvYgLQrctC10wyUHx5DljmVX6SMM+YmUbLIEX/gGcc5o8EfRdh/BhGWb0u3xEq6DWeVxrTXUiIkbsgV2YjMhL2BnTUlwaJ4Gyzb3VUc/psUzU3PqsBqIfikFSjOzXVxBFP0/8GUBCaPbya7UkxlEBGdS0JEjxNRY9y"
    }
  }
}
