kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-radarr-config
  namespace: media
spec:
  storageClassName: synology-storage-apps
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
