kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-radarr-config
  namespace: media
spec:
  storageClassName: synology-storage-apps
  volumeName: pvc-d758942b-51e3-435b-bf4e-14b078539cec
  # k patch pv pvc-d758942b-51e3-435b-bf4e-14b078539cec -p '{"spec":{"claimRef": null}}'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
