kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-sonarr-config
  namespace: media
spec:
  storageClassName: synology-storage-apps
  volumeName: pvc-1f71c5bc-f659-4310-8fb7-46c346420f05
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
