kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-prowlarr-config
  namespace: media
spec:
  storageClassName: synology-storage-apps
  volumeName: pvc-5b09e37c-b3e7-4e55-afc4-45c2094bbc85
  # k patch pv pvc-5b09e37c-b3e7-4e55-afc4-45c2094bbc85 -p '{"spec":{"claimRef": null}}'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
