kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-sabnzbd-config
  namespace: media
spec:
  storageClassName: synology-storage-apps
  volumeName: pvc-da088831-31e2-4557-a4c0-8f7b70b1f3ba
  # k patch pv pvc-da088831-31e2-4557-a4c0-8f7b70b1f3ba -p '{"spec":{"claimRef": null}}'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
