{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-api-token",
    "namespace": "cert-manager",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-api-token",
        "namespace": "cert-manager",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "cloudflare_api_token": "AgBlXQZQN+OhF4sN5D3E7eKjmU85vPolZCm+5XO0/MQQRxhKS5GW+HdYT+w07CMx0+jmHymxRAY87niD5UHByHpertAoSSkAdC1cqFL9U0C+0N1xLW9XcMHgx3tD/gzqDFTv3olXt0brNGARELblAd2kROTt2mP+9o/DK1SWWKEl8uibKwnmGt/At0zfHEn/+z2aPLa0diW9b3yKTumVtpA7w57wF2CXb6cvrBFxo+Vtnp7lfffHy3jKMN6k+3o+4kqnWC/J/A4kKOnXCc6LZ+IUZIJwN/pMDMzhoBcgy7l2zHoJIgX3nGfrP5CKJ9WV7MXK4fbe/UpbPVaLfC9hscS8I5Q04swYsI/Beq+QxBWGaxamtV9lv/vfU+xif0hvJMKbRXxdc0gUKN8Ezs1UntXEsvec1K0mD6QiTaIbxx2egqUffYdHIVPzFOQ9SnBPc5uyZjWYoV1a4hqORZ3uBl0vBXRki02K2mRavu/FhzW7WjP56NaGrK4jX72SKrcyOsWW6m3le4zzxJfthsHroT11QoV7xBPrXwn2F++t0m8hRK874Lp3QF4cFEWt9wBbYgPy1KTEU/DiXLk7xBUoaG+esxdum1hdwx4PKaYWqrFmThKMm10tyl0/tp1E7gci6Ci8EN7PFuoVNI4FRUrCGE/aSSPnFmis6sJcc5Czkv/XJcchijGqp2iOQwj+wR82rYAFGXHIxHgG+j07MHjDsV+BA0OW6ZWGiIkKDVhWBw6bMd00mBRyVVMA"
    }
  }
}
