{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-api-token",
    "namespace": "cert-manager",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-api-token",
        "namespace": "cert-manager",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "cloudflare_api_token": "AgCE2APwON37S4+o7mmGQUgErrwhPszVpniOUMK/slEx+hJ7u8CoHWz3I2WLOZFAYFR+uK5Wa3PzZOJmTNS9tqgdDzR8eLQhPKE9toNvrMfvieDJipoGP5PMQP9okYWy5ThK8OI0GQVRF91u9FuMuXgn4FMJpULUFTHF0zb+yOnwgKx/rSN9EI8Bn833SW23HdAd0twMrt0mPAb1vB89H7uOZ1qGC3q9WWYzNIbd5NF+Vx5qGtu+T83VG1xqcJ1+t5YQVMsiRpQyjLo/z/q3oEr9QM8tehkxqSIzBeJPDoZmT1n9i1aM9cvsQBu8ACOAxTo3Uv3cdOvENDKpnlFGRdnHbuPy2gt4lX9FSYIobYtYaFMV65Zt1qOCdjS5rWRpOiiK7a+ZeSld2P9MGu66oK13GlFqvpWBXxki4J7Nfuvlz4W91EDIUAErmto63x3GPgqGO33sKIoYQ2viLQSx0SiJndvH6GbI6JRZVH7bMnOPlFvsiLxhb9zVZZHNGnEllw0IWGKTvOm7Wg6VYoEDGMhO66HodBtMWqZ1FHXsxhIjHOWdepvmudK4RNcC0U9IxK1vwqFNnB5eEqnIGzBqbCIckfMv1NaQnZkIT5+G6TOi6ngQcbpvk5t+9D1B+4AAOm7puYs62Oa84kA0WevE57pHS80GCp/Fq03Ye9zMvDolj0be70dGO9qyzdrE/lrxdcWDe7HlPxiCaaSSY8h6ilg2+/+LR7olJ/tND9R45gwHCMvb5cnw9/ND"
    }
  }
}
