apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- letsencrypt-production.yaml
- letsencrypt-staging.yaml
- letsencrypt-wildcard-cert-pengiuns.com-production.yaml
- letsencrypt-wildcard-cert-pengiuns.com-staging.yaml
# the last two are in a separate namespace