apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: letsencrypt-wildcard-cert
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: benisekj@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - selector:
        dnsZones:
          - "pengiuns.com"
      dns01:
        cloudflare:
          email: benisekj@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: cloudflare_api_token