apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-tunel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgAdPVrRfS7KKUNmVXo5FcyEBUJIWiFWYx4niOGJwXLfBJ3D6qKNFG6jORKo6tnku1IEX8ZMG6OVVwmZIVH3Q1ZBqlcgKDZdw8MDbwJJ2Pnd0EF5w+TTbIxdYvStCFSiNleyGNQ91w+Hg4znLhaFXp0qxNh4eULpDemAOipc+rYi4SD3bPxpfJ28RUpfSppAeZk1HFJpRMw/dox1z48x8hcBKX+4lWXq/gRaKLxt+30pd6HsCxNsxK+E1VhhLrta9vMUJ20dm0ATwy1bntZoL/+8e9aTO9ZVbp0NG0U+WywXzedCKNwALGaI0uD3SbF8deVNqIWWIifa1Vwf6dtO0pqU166VHvhnRUjAvEW3nDPe/DTKbrdl09i1Zuzg+gY/9iX1KJsLFdAyRhFp08fSqdwH9kSzQhdFmu6YcskJlGfkuMdiuIVL5RO3fTWt0GNN38K244bA+VpTuVAuPwqQLyNDWfv3USIuNVi5KJ8Opex9+Tizm6893oZMKJMZLWkId6pCXb1MDf/kuX7NuggDabtz3bsInXa22z+sLkQWwsBkEMk1bBIWRr2++BFmo0SsijC3lK7TQRG9Qozuhudg5VAzLS0NLaYWzzk4C3FHV/DAeo3GLZFaMuHMSYfzSJaRbNKTbTJ9VPkjAxWo6QDhEZ6gosxeNUI3KqnQNfL4z9KJswQKQo/vfNaoKWtPfUq6vfwNIQQx2w0TCdFJALHeHzuO7gnesMgSM2mGXA9mBPsgU9XU9XxYc5X0PI+Hrro53Lgz9LypP43jXVUzDFNHY2DTUo0R3MDuHSYOYmxnVGwIQJBzlJKEiTVnyUSG7KJKQXR6zHxx9c5qnKo2gRG4rWzu+ax+ZP39Kcbya3hT092FrzzFrSFj5o6VBdyNO1Vrt7Ucnijg1oel9CbxcjUP+0rGEY9OSnRfpS4QXr0mnndB
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-tunel-credentials
      namespace: cloudflare
    type: Opaque

