apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: collabora
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: gru
  sources:
  - repoURL: https://collaboraonline.github.io/online/
    chart: collabora-online
    targetRevision: "1.1.60"
    helm:
      valueFiles:
      - $values/argocd/manifests/prod/apps/collabora/values.yaml
  - repoURL: https://github.com/JanBenisek/gru-ops.git
    targetRevision: main
    path: argocd/manifests/prod/apps/collabora
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: collabora
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
