apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: gru
  sources:
  - repoURL: ghcr.io/immich-app/immich-charts
    chart: immich
    targetRevision: "0.10.3"
    helm:
      valueFiles:
      - $values/argocd/manifests/prod/apps/immich/values.yaml
  - repoURL: https://bjw-s-labs.github.io/helm-charts
    chart: app-template
    targetRevision: "4.6.0" # TODO: bump to 4.6.0
    helm:
      valueFiles:
      - $values/argocd/manifests/prod/apps/immich/proxy-values.yaml
  - repoURL: https://github.com/JanBenisek/gru-ops.git
    targetRevision: main
    path: argocd/manifests/prod/apps/immich
    ref: values
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true