apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: libretranslate
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: gru
  source:
    repoURL: https://github.com/JanBenisek/gru-ops.git
    targetRevision: main
    path: argocd/manifests/prod/apps/libretranslate
  destination:
    server: https://kubernetes.default.svc
    namespace: libretranslate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true