apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metabase
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: gru
  sources:
  - repoURL: https://pmint93.github.io/helm-charts
    chart: metabase
    targetRevision: "2.22.2"
    helm:
      valueFiles:
      - $values/argocd/manifests/prod/apps/metabase/values.yaml
  - repoURL: https://github.com/JanBenisek/gru-ops.git
    targetRevision: main
    path: argocd/manifests/prod/apps/metabase
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: metabase
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true