apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: gru
  sources:
  - repoURL: https://helm.openwebui.com/
    chart: open-webui
    targetRevision: "13.0.1"
    helm:
      valueFiles:
      - $values/argocd/manifests/prod/apps/open-webui/values.yaml
  - repoURL: https://github.com/JanBenisek/gru-ops.git
    targetRevision: main
    path: argocd/manifests/prod/apps/open-webui
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: open-webui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true