apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secret-replicator
  namespace: secret-replicator
spec:
  chart:
    spec:
      chart: secret-replicator
      version: 0.6.x
      sourceRef:
        kind: HelmRepository
        name: kiwigrid
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: secret-replicator
  values:
    image:
      repository: kiwigrid/secret-replicator
      tag: 0.2.0
      pullPolicy: IfNotPresent
      ## Specify ImagePullSecrets for Pods
      ## ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
      # pullSecrets: myregistrykey

    # csv list of secrets
    secretList: "letsencrypt-wildcard-cert"
    # secretList: "secret1,secret2

    ignoreNamespaces: "kube-system,kube-public"

    # If defined, allow secret-replicator to watch for secrets in _another_ namespace
    secretNamespace: "letsencrypt-wildcard-cert"

    rbac:
      enabled: true

    resources: {}
      # limits:
      #   cpu: 50m
      #   memory: 20Mi
      # requests:
      #   cpu: 20m
      #   memory: 20Mi

    nodeSelector: {}

    tolerations: []

    affinity: {}
    