apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: immich-backup-manual
  namespace: immich
spec:
  # Another option to select, but not needed
  # labelSelectors:
  #   - matchExpressions:
  #     - key: back-me-up
  #       operator: Exists
  backend:
    s3:
      endpoint: https://hel1.your-objectstorage.com
      bucket: pengiunsbackup/immich/manual/
      accessKeyIDSecretRef:
        name: hetzner-credentials
        key: username
      secretAccessKeySecretRef:
        name: hetzner-credentials
        key: password
    repoPasswordSecretRef:
      name: restic-credentials
      key: password
  podSecurityContext:
    runAsUser: 0
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "500m"