{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "bot-immich-pswd",
    "namespace": "immich",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "bot-immich-pswd",
        "namespace": "immich",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "password": "AgAspRDxGxyvkQv5W2ujKqFqV77uKBUHZANvO7X/m4m12GgQYvkVm+pEZzxKHqZPTN6QLB96DbUfeDg4rFTuFZ4TnBeR+V2MgQI3EklMF0lFYME0dAQrS2xTOhy7vIzjRmWv/7Rpj3p1RTV9LQ0UcR3rsdTCx8lYd38zph6MiyXmpBKKFFEqh1xPlDcN9Be1rDUiNw4+cEJGipZVi7SU9sLis4YKkBG3duBMfI4OLGGSMAoieRxFOM5gGUeKbexLSvzc5A0rPgp+4snKmL45rPMQbKoCz/JdE+zDWtTySENpTjddRWQukSMZYQmeVGswRi1gbwq6w16kjbNmeAciQ49OSlpB6qY/Oat9J4X5fjjTPIKQ21G3qZMF7pdHyFlyeSwMpPKdaRvh0tPHg7cybOMMHXbFdS1VL56lxz/5CWbQ2SFFv9cdmdh7VeDt0x9tf7ut2HRSJFKiCexrSynEa55fHVL4SBI9IaEzc8WxHbEwPgUKVYq5M3nbzBqso7IXGqwZh8U37NfXM3cOK4gX84dSpPAltyNVu9kOqRyVJ3cw0An8NiKx6umE1LF3L8Bt2FP3UVKD4jjiQSRSFtDrxbKLUcKx4OxQASHdeiFB5yfyHnynC28Zzh/uo6NPEhkdwqhvkU1tK1D17Cl+WXqcU3FRKzcsSJzSazrRC4yTE0E0ISAzenzQlaQN3dqgalQT65Jb4y0SoEUd3xGjVVBM3vbhvE9d50iZ9SmXUBuz2JI="
    }
  }
}
