{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "bot-immich-pswd",
    "namespace": "immich",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "bot-immich-pswd",
        "namespace": "immich",
        "creationTimestamp": null
      },
      "type": "kubernetes.io/basic-auth"
    },
    "encryptedData": {
      "password": "AgA0tj4asl/noQJY8j0m59ePj+cOgxQj9Q/jr0Vt89brKEe2aIEFELykt7ZU8iBcHGxyybwpxiVYIz+MGZhzT+dP7H0jD3De1wNYL76OUTar0sZ6MKvBIQWTxV7fJrYX+npg9sIBj2IEtCfuI5shbGSXGjCy/slRsL0th5dWauoJoyFIsiIxCuLhIjl/nX7GAsyMTXOfzWvEkOsHFj010coMwD1iskaK9oP8YCPwTOoXHnni0IZU3D2z3GdQq7r79gMWwBABhXvO4uGCba5PMkjI445OhdIlMoJdz/C9gGHRhFYNKwPCE/inSeAdaK2lQOwPrTbhyad8w9QJHV5+wqfxtNtdmu7lvJihoTyq3OdilSHVpdz2cFTZGKMTpVJ6rVBLL6vg2hnko2JAzvL57UBEoRg91woiWVKrndB0eKqrnNzuOBjIBWE3C15dgc0xI2PmJyEQYcIbAMjtXKEh7eKZ7xymYRFmJRrIhEAxTCEtc7n6VF1386sX8SDLta5DtHZMBXgi/NXs/tYuPDtM1wCU/w1J35VojXCCZwI5dGO6eaJRcG7GSzTc2d+Y6DGngDUCm9NecYRlmPJALCi0xWiBJ50H08iOKESksyqjKCs0aYZJXKTsFhoviVXnUIsrp+mBaeCVCO18OdV6BbrZimO0B4bhcCKk3dFNui1uFRFrbDx+KeeDvMx8J1/hDkUQa7LZTg0//mIHpcMy6GgozZ18EUQ0E9dbeb40tdXZDlk=",
      "username": "AgBUgWsC2pjQ8YHilIaifSzUnKYoM6Golh9Q5QaRQ7NkzRrskdr4beMYGbotPt/mVyxIXRTyKmv/8so9PolYyem2iQfYqoQrUCT+2xrFcrlsYfL0YdJhqIRsjsCXOfPQiAeR6UdzlxXBmwg2yIrxAogU6IDDcyPNXtzrMGwCaocdSDeu41JyI1QoHHvT+n4faoFJM6/DRmBTR0n9IiSbflpIOfC72fINlzxcKoY9FWQbPA2kNosrlFGKnIs32GX6CrDk+h1RDwfNeCR16U3rcE+kHLSBy5IULmJZAw+0AcWeseWpY2ISTGRcM3u+tyr3MfPzOzqWgDc38rFt1bXUq+UPJY+SFoZ9fvuODlTbJIOZqI5ZNvhKZeWDGJ9iJPfxrvpdU4qKAjtsZM9F0fGSZfTEflXmjj/lXug996Y9Mhc5UrPR34i+5Esv/MLQrYZkVu/Atk4faTBaH8HPd3/8vI5zg1zaQAD5/olTBYtOaHbrna6LD9TOjG1dxi65czJ6xYZy3g++9qyCzQI8MXOxorZjt/kjScz8slwM0WMILXAQpmvd19wiYerd6R6aElc5vWAZb2KWGzeaFyzK9lF6M470D5OyrucvwrWmHCJarQSo9Jt5BhmhVKjl25nDwxfoz7Newqnb+1kj/jrGgxeFcXSCruNJ3Noh7jRFBHGgfCta5hYR7CuJ+Skf3wkRBoXFXjcJENtKJrajJgrQ"
    }
  }
}
