{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "hetzner-credentials",
    "namespace": "immich",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "hetzner-credentials",
        "namespace": "immich",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "password": "AgByWeYHSCdtI5pGaQ7+y1Z6lsF+P5Iw9TvOqTonldLnUrnyXcb51nGaqUQ10M6c9HkKS+oLl/2QalHV+kW87bJbiFCd+uOYnQ8Tbb5l9qK370gQibtiYDjrY5t6UKDbq7NMvgYI6o03+pg/KmYVf1b2fPuxSj1NT2Wg7/mM7yDwR3QgjmVXawszbmV76q6ZtMcLsykzP4WqyHGKOpbhzVaaz6qqEXCjnXls1giBf3TVi6nv3w7lHrp0kx8A1urt7sKGyUqVAIQEBmmMx9DRxYQ83guwBXuelHtJToose4vRztTiJ4pphP/WnjpjgmSuAAdP0DKiTfg5ND5oiSOb93z+z2zRbZU35p9OM2WiFMk1vInLXpcoAerzsqC96KHh1j9bCIPqiqc2GgQExwWmXxddF7C1MTvl56Ji8uCkT8gE529brP2ZxkdGr50mH1IyR1g1ofnxKDQBXmrvqPGj4gneW+oQqx1sKTrDUeQT4rUJWzq2zCEEnnMhMgA5GeobYI2Y/nBeaizhD99hZrIU8MmosdxZfJk4CamhPs0SDkvqexOW1RN9c8S7MCeoN2AXqP6nIGA99czV+83pdHrOSsgPSaOjgMQc8rw/2OCDe2KD8K8zvIMJXzE9GY1B9QdbnP094ByguE9rbu5YCGE9KBQhVcFdFie4/5yl4ofpl9YScvxnzmiJ0NBVR6iANGxArYCJ+JVj5Qg94jAOZE9GuzIOZEr8/ZN7AoD1Y+uJPbiY0XULbDxCn6gq",
      "username": "AgAdYM2NNoa81c1ChzCOoWMOfrQZ94XURRCmVrAqz4mMfqX1lD4g/t8OZN320O8ECWZCG12R7LEGbQuFrKCgXsklxcZLvM80NUZCs1uwXbALTDWxO3Fne0OADb+S0c4RWtx+0W7oFLFpceVW1cGtrG3d6XpnN/Sch9i2CKtZy6i9uwh+JZSJmI89A29QcRIlnrVeunNgMOaBCYA+2zD2uTyww47HToH+cLUa5zxLnhRGmYJ2KgMGviTtWDmOtoga0iy95ACV11F79phxj/PEwP5FIzTKAvTHICKNp3P+5o950Hk1L4R/bfz5eL7lgpqTw6s0BpMpJ/PNBWvKlip0C1RWYxf+6jNMaau4/qjOecYAp9c9hga2fGsrLbZpou7hgz0ahcmh2Sgw3/4l89DYfjvINUQxg7orGVE+nylBjFE6GLbc5dwy3lSnc5XjLRPUht/ohHc7NSjgWVa01MXPET+Z2oaPMAbF69OTGH50auYX5o0xE3wIFrsgVI2ejU0Cv5wqL8Nr291jc/6CN3QSeYZJ9cZYvT6Jx1zL3eKIAF1kMrYpImuZVyTJC/9PxnqsheK+fG/+FW3WGuYAebKJRoGJOGRlNIKRg4udBRorIDshBHa3taWnMz+XazetvzO7G2y4OvPaG9wDRpDHoBPu4TPCJrmf/MwhObhvTOx5+VDvfFjZw/dq99nKtkKrtdb07ypb8LhjInpQtjlyHZsMf1PuzlHfZg=="
    }
  }
}
