apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - bot_immich_pswd.yaml
  - namespace.yaml
  - pvc-immich.yaml
  - release.yaml
  - repository.yaml
  # DELETE
  # - hetzner-credentials.yaml
  - restic-credentials.yaml
  - backup-immich.yaml

