kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-immich
  namespace: immich
spec:
  storageClassName: local-hostpath-kevin
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
