apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-proxy
  namespace: immich
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: "1.4.0"
      sourceRef:
        kind: HelmRepository
        name: immich-proxy
        namespace: immich
      interval: 12h
  values:
    global:
      nameOverride: immich-proxy

    image:
      repository: alangrainger/immich-public-proxy
      tag: "1.5.4"
      pullPolicy: IfNotPresent

    env:
      IMMICH_URL: http://immich-server:2283 # from k get svc -n immich
      # https://github.com/alangrainger/immich-public-proxy/blob/main/app/config.jsont
      CONFIG: |
        {
          "ipp": {
            "singleImageGallery": true,
            "downloadOriginalPhoto": false,
            "allowDownloadAll": false,
            "showHomePage": false
          }
        }

    service:
      main:
        enabled: true
        primary: true
        type: ClusterIP
        ports:
          http:
            enabled: true
            primary: true
            port: 3000
            protocol: HTTP

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          # extra, see hiker readme
          nginx.ingress.kubernetes.io/ssl-redirect: "false" # do not redirect HTTP to HTTPS
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP" # not it expects HTTP from cloudflare
          nginx.ingress.kubernetes.io/proxy-redirect-from: "http://" # telling how to redirect
          nginx.ingress.kubernetes.io/proxy-redirect-to: "https://"
          # disable /preview - needs to enable server snippets on ingress
          # nginx.ingress.kubernetes.io/server-snippet: 'location ~* "^/share/photo/.*/preview" { return 403; }'
        hosts:
          - host: immich-share.${DOMAIN_NAME}
            paths:
              - path: "/"
                pathType: Prefix
        tls:
          - secretName: letsencrypt-immich-share-pengiuns-com
            hosts:
              - immich-share.${DOMAIN_NAME}

    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"