{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "restic-credentials",
    "namespace": "immich",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "restic-credentials",
        "namespace": "immich",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "password": "AgAZhRKtGAj2wwNQmHFlaTfoDFSwkSE0J2CXRc4HMHjmGXouiKlcvxHY4IJF/9W4ft877nY8clRvCNu7cjOvqSYYkPBcaUSqR6/SQCvdpVH3fRFYZzz1EK9He0MMgS65IIxtoWsJFhrR0IZ1joeetS3cf1VaKr+hog5Mm2qgG302VxgQOAsAQFhAZYpfA0Ep0POGOrBUshtZWvwL+R4yZI9j1ueVqCwceMoK+zYeR2sQbP3JJ/ee+TrH4fuluZSivAGQGKGRLvUx3MEow+rFYITzmfSZqXbT16eedGgtCYRd0OJkZZRrZ0P+SMnlGQqJiucyJIDMOKDp0OWlE/k8+MUPwVUExjKnDPB7R0nJvI6fs/Jrfco43W/5Ws59PwL4//65UWvjw9c5NUZgkasTIlumRx/NbilfIGYu4sJAy/iYTQAHOLjvnim/FAIYY3CfjJ6t7tC9cFHmDOFqx+YPz7u9FSQJ9UdWC1gJUYychcGNQeOgIf0TWjpNZwbk/aNPzZxloHF786L4MyMVGvZnaiJItmrc8QQVZfj4gzylnBxql5Dy72em3othJ6z/vAvih90L6I4LzlTnBnrOnp3jy7h12+RXn70P26+CyLLmhm+o5/aIRzDIMqsswya7gC5OaFNAsJX2JrmX1aeoqR8ajzJNc7a+qM16W0IeyuYa3fxw17lzFe6hVLFrOJ0pAb5ynMBPvtorndxwDDVfPUHBZk33yccQ4UJP1I8qcxpZRERu"
    }
  }
}
