kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-sabnzbd-config
  namespace: media
spec:
  storageClassName: synology-storage-configs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
