replicaCount: 1

url: "https://outline.pengiuns.com"
defaultLanguage: en_US

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "3000"

extraEnvVars:
  NODE_ENV: "production"
  TZ: "Europe/Zurich"
  # Pocket-ID
  OIDC_CLIENT_ID: "93fe5647-3be0-4960-966d-873bb00f2dff"
  OIDC_CLIENT_SECRET: "Ov1tZW1BAJ7KCEbZ9KWFyBD750ooQMI1"
  OIDC_AUTH_URI: "https://pocket-id.pengiuns.com/authorize"
  OIDC_TOKEN_URI: "https://pocket-id.pengiuns.com/api/oidc/token"
  OIDC_USERINFO_URI: "https://pocket-id.pengiuns.com/api/oidc/userinfo"
  OIDC_LOGOUT_URI: "https://pocket-id.pengiuns.com/api/oidc/end-session"
  OIDC_DISPLAY_NAME: "Pocket ID"
  OIDC_USERNAME_CLAIM: "preferred_username"
  OIDC_SCOPES: "openid profile email groups"

replicaCount: 1
strategy:
  type: RollingUpdate

logging:
  level: debug # error, warn, info, http, verbose, debug and silly

image:
  repository: outlinewiki/outline
  pullPolicy: IfNotPresent

ingress:
  enabled: false 

resources:
  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 512Mi

redis:
  enabled: true

postgresql:
  enabled: false

externalPostgresql:
  host: "vchord-postgres.pengiuns.com"
  username: "bot_outline"
  password: ""
  port: 5432
  database: outline
  existingSecret: "bot-outline-pswd"
  passwordSecretKey: "password"

minio:
  # -- Enable minio
  enabled: false

fileStorage:
  mode: local
  local:
    rootDir: /var/lib/outline/data
    persistence:
      enabled: true
      size: 20Gi
      accessModes:
        - ReadWriteOnce
      storageClass: "synology-storage-apps"
      # annotations:
        # backup.kubernetes.io/enabled: "true"