# docker build -t docker-registry.pengiuns.com/jupyter:rust -f Dockerfile-rust .
# docker push docker-registry.pengiuns.com/jupyter:rust
# docker run --rm -it --entrypoint /bin/bash docker-registry.pengiuns.com/jupyter:rust

FROM quay.io/jupyter/minimal-notebook:7830074b9e0a

USER root

ARG RUST_VERSION=nightly

RUN apt-get update && \
    apt-get install -y curl build-essential && \
    curl https://sh.rustup.rs -sSf | sh -s -- -y && \
    . "$HOME/.cargo/env" && \
    rustup install ${RUST_VERSION} && \
    rustup default ${RUST_VERSION} && \
    rustc --version && \
    cargo --version && \
    cargo install evcxr_jupyter && \
    evcxr_jupyter --install && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

USER jovyan

ENV PATH="/home/jovyan/.cargo/bin:/root/.cargo/bin:${PATH}"

