kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-jupyter-shared
  namespace: jupyter
spec:
  storageClassName: local-hostpath-kevin
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
