apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jupyter
  namespace: jupyter
spec:
  interval: 30m
  chart:
    spec:
      chart: jupyterhub
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: jupyterhub
        namespace: jupyter
      interval: 12h
  values:
    