apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jupyter
  namespace: jupyter
spec:
  interval: 30m
  chart:
    spec:
      chart: jupyterhub
      version: "4.2.0"
      sourceRef:
        kind: HelmRepository
        name: jupyterhub
        namespace: jupyter
      interval: 12h
  values:
    # TODO: remove user-scheduler?
    # figure out persistence
    # inspire from data-gitops
    # more differnt options and resources
    # read docs and fine-tune!
    debug:
      enabled: True

    hub:
      db:
        type: sqlite-memory # should not need PVC, change later

      config:
        JupyterHub:
          admin_access: true
          authenticator_class: dummy
          log_level: 'DEBUG'
          # TODO: use secret
          proxy_auth_token: 93b2706b1babfb2f74a33ca51cfa592d94c8309298735b9526d83ed3d87e0ed4

    proxy:
      #  openssl rand -hex 3
      #  read with echo ... | base64 -d
      secretToken: 93b2706b1babfb2f74a33ca51cfa592d94c8309298735b9526d83ed3d87e0ed4

    singleuser:
      defaultUrl: "/lab" # default Jupyter

      storage: # no storage for users
        type: none
      
      extraEnv:
        EDITOR: "vim"
        GRANT_SUDO: "yes"
        NOTEBOOK_ARGS: "--allow-root"

      image:
        name: jupyter/minimal-notebook
        tag: 7830074b9e0a
        pullPolicy: Always
      
      profileList:
        - display_name: "Tiny"
          description: "Python, [1/2 CPU, 1-5G RAM]"
          default: true
          kubespawner_override:
            cpu_guarantee: 0.5
            mem_guarantee: 1G
            cpu_limit: 1
            mem_limit: 5G
        - display_name: "Chonky boi ༼ つ ◕_◕ ༽つ🍰"
          description: "Python, [2 CPU, 10-15G RAM]"
          kubespawner_override:
            cpu_guarantee: 2
            mem_guarantee: 10G
            cpu_limit: 2
            mem_limit: 15G
        - display_name: "I love p-values"
          description: "R, [1/2 CPU, 1-5G RAM]"
          kubespawner_override:
            image: jupyter/r-notebook:7830074b9e0a
            cpu_guarantee: 0.5
            mem_guarantee: 1G
            cpu_limit: 1
            mem_limit: 5G

    # Pre-pulls images on new nodes, useful for autoscaling, not needed
    prePuller:
      hook:
        enabled: false 
      continuous:
        enabled: false 

    # Efficiently packing pods on a node, not needed
    scheduling:
      userScheduler:
        enabled: false 

    # Rules to remove inactive pods (see all default values)
    cull:
      enabled: true
      adminUsers: true 
      timeout: 1800 # 30 mins
      every: 600 # 10 minutes

    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/proxy-body-size: 100m
      hosts:
        - jupyter.${DOMAIN_NAME}
      tls:
        - secretName: letsencrypt-wildcard-cert-pengiuns.com-production
          hosts:
            - jupyter.${DOMAIN_NAME}

