apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sandbox
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  storageClassName: synology-storage-sandbox
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.178.96
    path: /volume1/sandbox
  persistentVolumeReclaimPolicy: Delete
