kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc2-hiker
  namespace: hiker
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  storageClassName: synology-storage-apps
  accessModes:
    - ReadWriteOnce # for normal pvc
  resources:
    requests:
      storage: 1Gi
