kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-hiker
  namespace: hiker
spec:
  storageClassName: synology-storage-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # volumeName: pv-hiker # this is static definition, dynamic creates PV automatically, which seems recommended
  # Keep it as an example now!
