kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc2-hiker
  namespace: hiker
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  storageClassName: synology-storage-configs
  accessModes:
    - ReadWriteOnce # for normal pvc
  resources:
    requests:
      storage: 1Gi
  # volumeName: pv-hiker # this is static definition, dynamic creates PV automatically, which seems recommended
  # Keep it as an example now!
