apiVersion: v1
kind: Service
metadata:
  name: hiker
  namespace: hiker
  labels:
    app.kubernetes.io/name: hiker
spec:
  selector:
    app: hiker
  type: ClusterIP
  # type: LoadBalancer
  # loadBalancerIP: 192.168.178.200 # fixed IP for cloudflare to reach it (also handy for debugging)
  ports:
  - name: http
    port: 80 # we talk to 80
    protocol: TCP
    targetPort: 8080 # app listens here