apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tinyauth
  namespace: tinyauth
  labels:
    app: tinyauth
    app.kubernetes.io/name: tinyauth
spec:
  serviceName: tinyauth
  replicas: 1

  podManagementPolicy: OrderedReady

  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0

  selector:
    matchLabels:
      app: tinyauth
  template:
    metadata:
      labels:
        app: tinyauth
        app.kubernetes.io/name: tinyauth
    spec:
      containers:
      - name: tinyauth
        image: ghcr.io/steveiliop56/tinyauth:v4
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        env:
          - name: APP_URL
            value: https://tinyauth.pengiuns.com
          - name: USERS
            # htpasswd -nbB corgi ilovecorgi
            value: corgi:$2y$05$FoIrOW55cZYshGDEyQokcOAhZZ2wfePbKiAFEAlTetNaGlk5Jc0zK
            # value: user:$$2a$$10$$UdLYoJ5lgPsC0RKqYH/jMua7zIn0g9kPqWmhYayJYLaZQ/FTmH2/u # Username is user and password is password
          - name: LOG_LEVEL
            value: debug
          - name: SESSION_EXPIRY
            value: "86400"  # Session expires after 24 hours (86400 seconds)
          - name: LOGIN_TIMEOUT
            value: "300"  # Login Atimeout: 5 minutes (300 seconds)
          - name: APP_TITLE
            value: Bello!
          # Figure out later
          - name: BACKGROUND_IMAGE
            value: "https://raw.githubusercontent.com/JanBenisek/public-assets/main/zermatt.jpg"
          # - name: RESOURCES_DIR
          #   value: ""
            
        resources:
          requests:
            memory: "128Mi"  
            cpu: "10m"      
          limits:
            memory: "1Gi"