apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: outline
  namespace: outline
spec:
  interval: 30m
  chart:
    spec:
      chart: outline
      version: "0.7.0"
      sourceRef:
        kind: HelmRepository
        name: outline
        namespace: outline
      interval: 12h
  values:
    replicaCount: 1

    logging:
      level: debug # error, warn, info, http, verbose, debug and silly

    ingress:
      enabled: true 
      className: "nginx"
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
        - host: "outline.${DOMAIN_NAME}"
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: letsencrypt-wildcard-cert-pengiuns.com-production
          hosts:
            - "outline.${DOMAIN_NAME}"

    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 512Mi
    
    redis:
      enabled: true

    postgresql:
      enabled: false

    externalPostgresql:
      host: "${POSTGRESQL_VCHORD_HOST}" 
      username: "bot_outine"
      password: ""
      port: 5432
      database: outline
      existingSecret: "bot-outline-pswd"
      passwordSecretKey: "postgres-password"

    minio:
      # -- Enable minio
      enabled: false
